// Generated by port/tools/gen_stubs.py. Do not edit by hand;
// override a stub by defining the symbol in another port/src file.

#include <Runtime/platform.h>
#include <dolphin/ai.h>
#include <dolphin/ar.h>
#include <dolphin/ax.h>
#include <dolphin/axfx.h>
#include <dolphin/base/PPCArch.h>
#include <dolphin/card.h>
#include <dolphin/card/CARDBios.h>
#include <dolphin/card/CARDCheck.h>
#include <dolphin/card/CARDCreate.h>
#include <dolphin/card/CARDDelete.h>
#include <dolphin/card/CARDMount.h>
#include <dolphin/card/CARDOpen.h>
#include <dolphin/card/CARDRdwr.h>
#include <dolphin/card/CARDRead.h>
#include <dolphin/card/CARDStat.h>
#include <dolphin/card/CARDWrite.h>
#include <dolphin/db.h>
#include <dolphin/dvd.h>
#include <dolphin/gx/GXBump.h>
#include <dolphin/gx/GXCull.h>
#include <dolphin/gx/GXDispList.h>
#include <dolphin/gx/GXFrameBuffer.h>
#include <dolphin/gx/GXGeometry.h>
#include <dolphin/gx/GXGet.h>
#include <dolphin/gx/GXLighting.h>
#include <dolphin/gx/GXManage.h>
#include <dolphin/gx/GXPixel.h>
#include <dolphin/gx/GXTev.h>
#include <dolphin/gx/GXTexture.h>
#include <dolphin/gx/GXTransform.h>
#include <dolphin/mcc.h>
#include <dolphin/mtx.h>
#include <dolphin/os.h>
#include <dolphin/os/OSAlarm.h>
#include <dolphin/os/OSAlloc.h>
#include <dolphin/os/OSCache.h>
#include <dolphin/os/OSContext.h>
#include <dolphin/os/OSError.h>
#include <dolphin/os/OSReset.h>
#include <dolphin/os/OSResetSW.h>
#include <dolphin/os/OSRtc.h>
#include <dolphin/os/OSThread.h>
#include <dolphin/pad.h>
#include <dolphin/thp/thp.h>
#include <dolphin/vi/vifuncs.h>

#define STUB __attribute__((weak))

STUB void AIInit(u8* stack) {}
STUB void AISetDSPSampleRate(u32 rate) {}
STUB void AISetStreamVolLeft(u8 vol) {}
STUB void AISetStreamVolRight(u8 vol) {}
STUB u32 ARAlloc(u32 length) { return (u32) 0; }
STUB u32 ARFree(u32* length) { return (u32) 0; }
STUB u32 ARGetSize(void) { return (u32) 0; }
STUB u32 ARInit(u32* stack_index_addr, u32 num_entries) { return (u32) 0; }
STUB void ARQInit(void) {}
STUB void ARQPostRequest(struct ARQRequest* request, u32 owner, u32 type, u32 priority, u32 source, u32 dest, u32 length, ARQCallback callback) {}
STUB AXVPB* AXAcquireVoice(u32 priority, void (*callback)(void*), u32 userContext) { return (AXVPB*) 0; }
STUB void AXFXChorusCallback(struct AXFX_BUFFERUPDATE* bufferUpdate, struct AXFX_CHORUS* chorus) {}
STUB int AXFXChorusInit(struct AXFX_CHORUS* c) { return (int) 0; }
STUB int AXFXChorusShutdown(struct AXFX_CHORUS* c) { return (int) 0; }
STUB void AXFXDelayCallback(struct AXFX_BUFFERUPDATE* bufferUpdate, struct AXFX_DELAY* delay) {}
STUB int AXFXDelayInit(struct AXFX_DELAY* delay) { return (int) 0; }
STUB int AXFXDelayShutdown(struct AXFX_DELAY* delay) { return (int) 0; }
STUB void AXFXReverbHiCallback(struct AXFX_BUFFERUPDATE* bufferUpdate, struct AXFX_REVERBHI* reverb) {}
STUB int AXFXReverbHiInit(struct AXFX_REVERBHI* rev) { return (int) 0; }
STUB int AXFXReverbHiShutdown(struct AXFX_REVERBHI* rev) { return (int) 0; }
STUB void AXFXReverbStdCallback(struct AXFX_BUFFERUPDATE* bufferUpdate, struct AXFX_REVERBSTD* reverb) {}
STUB int AXFXReverbStdInit(struct AXFX_REVERBSTD* rev) { return (int) 0; }
STUB int AXFXReverbStdShutdown(struct AXFX_REVERBSTD* rev) { return (int) 0; }
STUB void AXFXSetHooks(void* (*alloc_hook)(unsigned long), void (*free_hook)(void*)) {}
STUB void AXFreeVoice(AXVPB* p) {}
STUB void AXInit(void) {}
STUB void AXRegisterAuxACallback(void (*callback)(void*, void*), void* context) {}
STUB void AXRegisterAuxBCallback(void (*callback)(void*, void*), void* context) {}
STUB void AXRegisterCallback(void (*callback)()) {}
STUB void AXSetVoiceAddr(AXVPB* p, AXPBADDR* addr) {}
STUB void AXSetVoiceAdpcm(AXVPB* p, AXPBADPCM* adpcm) {}
STUB void AXSetVoiceAdpcmLoop(AXVPB* p, AXPBADPCMLOOP* adpcmloop) {}
STUB void AXSetVoiceCurrentAddr(AXVPB* p, u32 addr) {}
STUB void AXSetVoiceEndAddr(AXVPB* p, u32 addr) {}
STUB void AXSetVoiceItdOn(AXVPB* p) {}
STUB void AXSetVoiceItdTarget(AXVPB* p, u16 lShift, u16 rShift) {}
STUB void AXSetVoiceLoop(AXVPB* p, u16 loop) {}
STUB void AXSetVoiceLoopAddr(AXVPB* p, u32 addr) {}
STUB void AXSetVoiceMix(AXVPB* p, AXPBMIX* mix) {}
STUB void AXSetVoicePriority(AXVPB* p, u32 priority) {}
STUB void AXSetVoiceSrc(AXVPB* p, AXPBSRC* src_) {}
STUB void AXSetVoiceSrcRatio(AXVPB* p, float ratio) {}
STUB void AXSetVoiceState(AXVPB* p, u16 state) {}
STUB void AXSetVoiceVe(AXVPB* p, AXPBVE* ve) {}
STUB void AXSetVoiceVeDelta(AXVPB* p, s16 delta) {}
STUB s32 CARDCheckAsync(s32 chan, CARDCallback callback) { return (s32) 0; }
STUB s32 CARDClose(CARDFileInfo* fileInfo) { return (s32) 0; }
STUB s32 CARDCreateAsync(s32 chan, const char* fileName, u32 size, CARDFileInfo* fileInfo, CARDCallback callback) { return (s32) 0; }
STUB s32 CARDDeleteAsync(s32 chan, char* fileName, CARDCallback callback) { return (s32) 0; }
STUB s32 CARDFastOpen(s32 chan, s32 fileNo, CARDFileInfo* fileInfo) { return (s32) 0; }
STUB s32 CARDFormatAsync(s32 chan, CARDCallback callback) { return (s32) 0; }
STUB s32 CARDFreeBlocks(s32 chan, s32* byteNotUsed, s32* filesNotUsed) { return (s32) 0; }
STUB s32 CARDGetStatus(s32 chan, s32 fileNo, CARDStat* stat) { return (s32) 0; }
STUB long CARDGetXferredBytes(long chan) { return (long) 0; }
STUB void CARDInit(void) {}
STUB s32 CARDMountAsync(s32 chan, void* workArea, CARDCallback detachCallback, CARDCallback attachCallback) { return (s32) 0; }
STUB s32 CARDOpen(s32 chan, const char* fileName, CARDFileInfo* fileInfo) { return (s32) 0; }
STUB BOOL CARDProbe(long chan) { return (BOOL) 0; }
STUB s32 CARDProbeEx(s32 chan, s32* memSize, s32* sectorSize) { return (s32) 0; }
STUB s32 CARDReadAsync(CARDFileInfo* fileInfo, void* buf, s32 length, s32 offset, CARDCallback callback) { return (s32) 0; }
STUB s32 CARDRenameAsync(s32 chan, const char* oldName, const char* newName, CARDCallback callback) { return (s32) 0; }
STUB s32 CARDSetStatusAsync(s32 chan, s32 fileNo, CARDStat* stat, CARDCallback callback) { return (s32) 0; }
STUB s32 CARDUnmount(s32 chan) { return (s32) 0; }
STUB s32 CARDWriteAsync(CARDFileInfo* fileInfo, void* buf, s32 length, s32 offset, CARDCallback callback) { return (s32) 0; }
STUB void C_MTXLookAt(Mtx m, Point3dPtr camPos, VecPtr camUp, Point3dPtr target) {}
STUB BOOL DBIsDebuggerPresent(void) { return (BOOL) 0; }
STUB void DCFlushRange(void* addr, u32 nBytes) {}
STUB void DCInvalidateRange(void* addr, u32 nBytes) {}
STUB void DCStoreRange(void* addr, u32 nBytes) {}
STUB BOOL DVDCheckDisk(void) { return (BOOL) 0; }
STUB BOOL DVDClose(DVDFileInfo* fileInfo) { return (BOOL) 0; }
STUB s32 DVDConvertPathToEntrynum(const char* pathPtr) { return (s32) 0; }
STUB BOOL DVDFastOpen(s32 entrynum, DVDFileInfo* fileInfo) { return (BOOL) 0; }
STUB struct DVDDiskID* DVDGetCurrentDiskID(void) { return (struct DVDDiskID*) 0; }
STUB long DVDGetDriveStatus() { return (long) 0; }
STUB void DVDInit() {}
STUB BOOL DVDReadAsyncPrio(DVDFileInfo* fileInfo, void* addr, s32 length, s32 offset, DVDCallback callback, s32 prio) { return (BOOL) 0; }
STUB void FIOExit(void) {}
STUB int FIOFclose(int handle) { return (int) 0; }
STUB int FIOFopen(const char* filename, u32 mode) { return (int) 0; }
STUB u32 FIOFwrite(int handle, void* data, u32 size) { return (u32) 0; }
STUB int FIOInit(enum MCC_EXI exiChannel, enum MCC_CHANNEL chID, u8 blockSize) { return (int) 0; }
STUB int FIOQuery(void) { return (int) 0; }
STUB void GXBegin(GXPrimitive type, GXVtxFmt vtxfmt, u16 nverts) {}
STUB void GXCallDisplayList(void* list, u32 nbytes) {}
STUB void GXClearVtxDesc(void) {}
STUB void GXCopyDisp(void* dest, GXBool clear) {}
STUB void GXCopyTex(void* dest, GXBool clear) {}
STUB void GXEnableTexOffsets(GXTexCoordID coord, u8 line_enable, u8 point_enable) {}
STUB void GXGetProjectionv(f32* ptr) {}
STUB u32 GXGetTexBufferSize(u16 width, u16 height, u32 format, u8 mipmap, u8 max_lod) { return (u32) 0; }
STUB GXTexFmt GXGetTexObjFmt(const GXTexObj* to) { return (GXTexFmt) 0; }
STUB u16 GXGetTexObjHeight(const GXTexObj* to) { return (u16) 0; }
STUB u16 GXGetTexObjWidth(const GXTexObj* to) { return (u16) 0; }
STUB void GXGetViewportv(f32* vp) {}
STUB GXFifoObj* GXInit(void* base, u32 size) { return (GXFifoObj*) 0; }
STUB void GXInitFogAdjTable(GXFogAdjTable* table, u16 width, f32 projmtx[4][4]) {}
STUB void GXInitLightAttn(GXLightObj* lt_obj, f32 a0, f32 a1, f32 a2, f32 k0, f32 k1, f32 k2) {}
STUB void GXInitLightColor(GXLightObj* lt_obj, GXColor color) {}
STUB void GXInitLightDir(GXLightObj* lt_obj, f32 nx, f32 ny, f32 nz) {}
STUB void GXInitLightDistAttn(GXLightObj* lt_obj, f32 ref_dist, f32 ref_br, GXDistAttnFn dist_func) {}
STUB void GXInitLightPos(GXLightObj* lt_obj, f32 x, f32 y, f32 z) {}
STUB void GXInitLightSpot(GXLightObj* lt_obj, f32 cutoff, GXSpotFn spot_func) {}
STUB void GXInitTexObj(GXTexObj* obj, void* image_ptr, u16 width, u16 height, GXTexFmt format, GXTexWrapMode wrap_s, GXTexWrapMode wrap_t, u8 mipmap) {}
STUB void GXInitTexObjCI(GXTexObj* obj, void* image_ptr, u16 width, u16 height, GXTexFmt format, GXTexWrapMode wrap_s, GXTexWrapMode wrap_t, u8 mipmap, u32 tlut_name) {}
STUB void GXInitTexObjLOD(GXTexObj* obj, GXTexFilter min_filt, GXTexFilter mag_filt, f32 min_lod, f32 max_lod, f32 lod_bias, GXBool bias_clamp, GXBool do_edge_lod, GXAnisotropy max_aniso) {}
STUB void GXInitTlutObj(GXTlutObj* tlut_obj, void* lut, GXTlutFmt fmt, u16 n_entries) {}
STUB void GXInvalidateTexAll(void) {}
STUB void GXInvalidateVtxCache(void) {}
STUB void GXLoadLightObjImm(GXLightObj* lt_obj, GXLightID light) {}
STUB void GXLoadNrmMtxImm(f32 mtx[3][4], u32 id) {}
STUB void GXLoadPosMtxImm(f32 mtx[3][4], u32 id) {}
STUB void GXLoadTexMtxImm(f32 mtx[][4], u32 id, GXTexMtxType type) {}
STUB void GXLoadTexObj(GXTexObj* obj, GXTexMapID id) {}
STUB void GXLoadTlut(GXTlutObj* tlut_obj, u32 tlut_name) {}
STUB void GXPixModeSync(void) {}
STUB void GXProject(f32 x, f32 y, f32 z, f32 mtx[3][4], f32* pm, f32* vp, f32* sx, f32* sy, f32* sz) {}
STUB void GXSetAlphaCompare(GXCompare comp0, u8 ref0, GXAlphaOp op, GXCompare comp1, u8 ref1) {}
STUB void GXSetAlphaUpdate(GXBool update_enable) {}
STUB void GXSetArray(GXAttr attr, const void* base_ptr, u8 stride) {}
STUB void GXSetBlendMode(GXBlendMode type, GXBlendFactor src_factor, GXBlendFactor dst_factor, GXLogicOp op) {}
STUB void GXSetChanAmbColor(GXChannelID chan, GXColor amb_color) {}
STUB void GXSetChanCtrl(GXChannelID chan, GXBool enable, GXColorSrc amb_src, GXColorSrc mat_src, u32 light_mask, GXDiffuseFn diff_fn, GXAttnFn attn_fn) {}
STUB void GXSetChanMatColor(GXChannelID chan, GXColor mat_color) {}
STUB void GXSetColorUpdate(GXBool update_enable) {}
STUB void GXSetCopyClamp(GXFBClamp clamp) {}
STUB void GXSetCopyClear(GXColor clear_clr, u32 clear_z) {}
STUB void GXSetCopyFilter(GXBool aa, const u8 sample_pattern[12][2], GXBool vf, const u8 vfilter[7]) {}
STUB void GXSetCullMode(GXCullMode mode) {}
STUB void GXSetCurrentMtx(u32 id) {}
STUB void GXSetDispCopyDst(u16 wd, u16 ht) {}
STUB void GXSetDispCopyGamma(GXGamma gamma) {}
STUB void GXSetDispCopySrc(u16 left, u16 top, u16 wd, u16 ht) {}
STUB u32 GXSetDispCopyYScale(f32 vscale) { return (u32) 0; }
STUB void GXSetDither(GXBool dither) {}
STUB void GXSetDrawDone(void) {}
STUB GXDrawDoneCallback GXSetDrawDoneCallback(GXDrawDoneCallback cb) { return (GXDrawDoneCallback) 0; }
STUB void GXSetDstAlpha(GXBool enable, u8 alpha) {}
STUB void GXSetFieldMode(GXBool field_mode, GXBool half_aspect_ratio) {}
STUB void GXSetFog(GXFogType type, f32 startz, f32 endz, f32 nearz, f32 farz, GXColor color) {}
STUB void GXSetFogRangeAdj(GXBool enable, u16 center, GXFogAdjTable* table) {}
STUB void GXSetIndTexCoordScale(GXIndTexStageID ind_state, GXIndTexScale scale_s, GXIndTexScale scale_t) {}
STUB void GXSetIndTexMtx(GXIndTexMtxID mtx_id, f32 offset[2][3], s8 scale_exp) {}
STUB void GXSetIndTexOrder(GXIndTexStageID ind_stage, GXTexCoordID tex_coord, GXTexMapID tex_map) {}
STUB void GXSetLineWidth(u8 width, GXTexOffset texOffsets) {}
STUB void GXSetMisc(GXMiscToken token, u32 val) {}
STUB void GXSetNumChans(u8 nChans) {}
STUB void GXSetNumIndStages(u8 nIndStages) {}
STUB void GXSetNumTevStages(u8 nStages) {}
STUB void GXSetNumTexGens(u8 nTexGens) {}
STUB void GXSetPixelFmt(GXPixelFmt pix_fmt, GXZFmt16 z_fmt) {}
STUB void GXSetPointSize(u8 pointSize, GXTexOffset texOffsets) {}
STUB void GXSetProjection(f32 mtx[4][4], GXProjectionType type) {}
STUB void GXSetScissor(u32 left, u32 top, u32 wd, u32 ht) {}
STUB void GXSetTevAlphaIn(GXTevStageID stage, GXTevAlphaArg a, GXTevAlphaArg b, GXTevAlphaArg c, GXTevAlphaArg d) {}
STUB void GXSetTevAlphaOp(GXTevStageID stage, GXTevOp op, GXTevBias bias, GXTevScale scale, GXBool clamp, GXTevRegID out_reg) {}
STUB void GXSetTevClampMode(int, int) {}
STUB void GXSetTevColor(GXTevRegID id, GXColor color) {}
STUB void GXSetTevColorIn(GXTevStageID stage, GXTevColorArg a, GXTevColorArg b, GXTevColorArg c, GXTevColorArg d) {}
STUB void GXSetTevColorOp(GXTevStageID stage, GXTevOp op, GXTevBias bias, GXTevScale scale, GXBool clamp, GXTevRegID out_reg) {}
STUB void GXSetTevColorS10(GXTevRegID id, GXColorS10 color) {}
STUB void GXSetTevDirect(GXTevStageID tev_stage) {}
STUB void GXSetTevIndirect(GXTevStageID tev_stage, GXIndTexStageID ind_stage, GXIndTexFormat format, GXIndTexBiasSel bias_sel, GXIndTexMtxID matrix_sel, GXIndTexWrap wrap_s, GXIndTexWrap wrap_t, GXBool add_prev, GXBool utc_lod, GXIndTexAlphaSel alpha_sel) {}
STUB void GXSetTevKAlphaSel(GXTevStageID stage, GXTevKAlphaSel sel) {}
STUB void GXSetTevKColor(GXTevKColorID id, GXColor color) {}
STUB void GXSetTevKColorSel(GXTevStageID stage, GXTevKColorSel sel) {}
STUB void GXSetTevOp(GXTevStageID id, GXTevMode mode) {}
STUB void GXSetTevOrder(GXTevStageID stage, GXTexCoordID coord, GXTexMapID map, GXChannelID color) {}
STUB void GXSetTevSwapMode(GXTevStageID stage, GXTevSwapSel ras_sel, GXTevSwapSel tex_sel) {}
STUB void GXSetTevSwapModeTable(GXTevSwapSel table, GXTevColorChan red, GXTevColorChan green, GXTevColorChan blue, GXTevColorChan alpha) {}
STUB void GXSetTexCoordGen2(GXTexCoordID dst_coord, GXTexGenType func, GXTexGenSrc src_param, u32 mtx, GXBool normalize, u32 pt_texmtx) {}
STUB void GXSetTexCopyDst(u16 wd, u16 ht, GXTexFmt fmt, GXBool mipmap) {}
STUB void GXSetTexCopySrc(u16 left, u16 top, u16 wd, u16 ht) {}
STUB void GXSetViewport(f32 left, f32 top, f32 wd, f32 ht, f32 nearz, f32 farz) {}
STUB void GXSetViewportJitter(f32 left, f32 top, f32 wd, f32 ht, f32 nearz, f32 farz, u32 field) {}
STUB void GXSetVtxAttrFmt(GXVtxFmt vtxfmt, GXAttr attr, GXCompCnt cnt, GXCompType type, u8 frac) {}
STUB void GXSetVtxDesc(GXAttr attr, GXAttrType type) {}
STUB void GXSetZCompLoc(GXBool before_tex) {}
STUB void GXSetZMode(GXBool compare_enable, GXCompare func, GXBool update_enable) {}
STUB void GXSetZTexture(GXZTexOp op, GXTexFmt fmt, u32 bias) {}
STUB void GXWaitDrawDone(void) {}
STUB int MCCClose(enum MCC_CHANNEL chID) { return (int) 0; }
STUB int MCCEnumDevices(MCC_CBEnumDevices callbackEnumDevices) { return (int) 0; }
STUB void MCCExit(void) {}
STUB int MCCGetConnectionStatus(enum MCC_CHANNEL chID, enum MCC_CONNECT* connect) { return (int) 0; }
STUB u8 MCCGetFreeBlocks(enum MCC_MODE mode) { return (u8) 0; }
STUB u8 MCCGetLastError(void) { return (u8) 0; }
STUB int MCCInit(enum MCC_EXI exiChannel, u8 timeout, MCC_CBSysEvent callbackSysEvent) { return (int) 0; }
STUB int MCCNotify(enum MCC_CHANNEL chID, u32 notify) { return (int) 0; }
STUB int MCCOpen(enum MCC_CHANNEL chID, u8 blockSize, MCC_CBEvent callbackEvent) { return (int) 0; }
STUB int MCCRead(enum MCC_CHANNEL chID, u32 offset, void* data, long size, enum MCC_SYNC_STATE async) { return (int) 0; }
STUB int MCCStreamOpen(enum MCC_CHANNEL chID, u8 blockSize) { return (int) 0; }
STUB int MCCWrite(enum MCC_CHANNEL chID, u32 offset, void* data, long size, enum MCC_SYNC_STATE async) { return (int) 0; }
STUB void MTXFrustum(Mtx m, f32 t, f32 b, f32 l, f32 r, f32 n, f32 f) {}
STUB void MTXLightFrustum(Mtx m, f32 t, f32 b, f32 l, f32 r, f32 n, f32 scaleS, f32 scaleT, f32 transS, f32 transT) {}
STUB void MTXLightOrtho(Mtx m, f32 t, f32 b, f32 l, f32 r, f32 scaleS, f32 scaleT, f32 transS, f32 transT) {}
STUB void MTXLightPerspective(Mtx m, f32 fovY, f32 aspect, f32 scaleS, f32 scaleT, f32 transS, f32 transT) {}
STUB void MTXOrtho(Mtx m, f32 t, f32 b, f32 l, f32 r, f32 n, f32 f) {}
STUB void MTXPerspective(Mtx m, f32 fovY, f32 aspect, f32 n, f32 f) {}
STUB void MTXRotRad(Mtx m, char axis, f32 rad) {}
STUB void* OSAllocFromArenaHi(u32 size, u32 align) { return (void*) 0; }
STUB void* OSAllocFromArenaLo(u32 size, u32 align) { return (void*) 0; }
STUB void* OSAllocFromHeap(int heap, unsigned long size) { return (void*) 0; }
STUB void OSCancelAlarm(OSAlarm* alarm) {}
STUB long OSCheckActiveThreads(void) { return (long) 0; }
STUB long OSCheckHeap(int heap) { return (long) 0; }
STUB void OSClearContext(OSContext* context) {}
STUB void OSCreateAlarm(OSAlarm* alarm) {}
STUB int OSCreateHeap(void* start, void* end) { return (int) 0; }
STUB int OSCreateThread(struct OSThread* thread, void* (*func)(void*), void* param, void* stack, unsigned long stackSize, long priority, unsigned short attr) { return (int) 0; }
STUB void OSDestroyHeap(int heap) {}
STUB BOOL OSDisableInterrupts(void) { return (BOOL) 0; }
STUB void OSFreeToHeap(int heap, void* ptr) {}
STUB void* OSGetArenaHi(void) { return (void*) 0; }
STUB void* OSGetArenaLo(void) { return (void*) 0; }
STUB u32 OSGetConsoleSimulatedMemSize(void) { return (u32) 0; }
STUB OSContext* OSGetCurrentContext(void) { return (OSContext*) 0; }
STUB u32 OSGetPhysicalMemSize(void) { return (u32) 0; }
STUB u32 OSGetProgressiveMode(void) { return (u32) 0; }
STUB unsigned long OSGetResetCode() { return (unsigned long) 0; }
STUB BOOL OSGetResetSwitchState() { return (BOOL) 0; }
STUB u32 OSGetSoundMode() { return (u32) 0; }
STUB OSTick OSGetTick(void) { return (OSTick) 0; }
STUB OSTime OSGetTime(void) { return (OSTime) 0; }
STUB void OSInit(void) {}
STUB void OSInitAlarm(void) {}
STUB void* OSInitAlloc(void* arenaStart, void* arenaEnd, int maxHeaps) { return (void*) 0; }
STUB void OSLoadFPUContext(OSContext* fpuContext) {}
STUB void OSReport(char*, ...) {}
STUB void OSResetSystem(int reset, u32 resetCode, BOOL forceMenu) {}
STUB BOOL OSRestoreInterrupts(BOOL level) { return (BOOL) 0; }
STUB s32 OSResumeThread(OSThread* thread) { return (s32) 0; }
STUB u32 OSSaveContext(OSContext* context) { return (u32) 0; }
STUB void OSSaveFPUContext(OSContext* fpuContext) {}
STUB void OSSetAlarm(OSAlarm* alarm, OSTime tick, OSAlarmHandler handler) {}
STUB void OSSetArenaLo(void*) {}
STUB void OSSetCurrentContext(OSContext* context) {}
STUB int OSSetCurrentHeap(int heap) { return (int) 0; }
STUB OSErrorHandler OSSetErrorHandler(OSError error, OSErrorHandler handler) { return (OSErrorHandler) 0; }
STUB void OSSetPeriodicAlarm(OSAlarm* alarm, OSTime start, OSTime period, OSAlarmHandler handler) {}
STUB void OSSetProgressiveMode(u32 mode) {}
STUB void OSSetSoundMode(u32 mode) {}
STUB void OSTicksToCalendarTime(OSTime ticks, OSCalendarTime* td) {}
STUB void PADClamp(PADStatus* status) {}
STUB void PADControlMotor(s32 chan, u32 command) {}
STUB BOOL PADInit() { return (BOOL) 0; }
STUB u32 PADRead(struct PADStatus* status) { return (u32) 0; }
STUB BOOL PADRecalibrate(u32 mask) { return (BOOL) 0; }
STUB int PADReset(unsigned long mask) { return (int) 0; }
STUB void PADSetSamplingRate(unsigned long msec) {}
STUB void PADSetSpec(u32 spec) {}
STUB u32 PPCMfmsr() { return (u32) 0; }
STUB void PPCMtmsr(u32 newMSR) {}
STUB void PSMTXConcat(Mtx mA, Mtx mB, Mtx mAB) {}
STUB void PSMTXCopy(Mtx src, Mtx dst) {}
STUB void PSMTXIdentity(Mtx m) {}
STUB u32 PSMTXInverse(Mtx src, Mtx inv) { return (u32) 0; }
STUB void PSMTXMultVec(Mtx44 m, Vec* src, Vec* dst) {}
STUB void PSMTXMultVecSR(Mtx44 m, Vec* src, Vec* dst) {}
STUB void PSMTXQuat(Mtx m, QuaternionPtr q) {}
STUB void PSMTXRotAxisRad(Mtx m, Vec* axis, f32 rad) {}
STUB void PSMTXScale(Mtx m, f32 xS, f32 yS, f32 zS) {}
STUB void PSMTXTranspose(Mtx src, Mtx xPose) {}
STUB void PSVECAdd(Vec* a, Vec* b, Vec* c) {}
STUB void PSVECCrossProduct(Vec* vec1, Vec* vec2, Vec* dst) {}
STUB f32 PSVECDotProduct(Vec* vec1, Vec* vec2) { return (f32) 0; }
STUB f32 PSVECMag(Vec* v) { return (f32) 0; }
STUB void PSVECNormalize(Vec* vec1, Vec* dst) {}
STUB void PSVECScale(Vec* src, Vec* dst, f32 scale) {}
STUB void PSVECSubtract(Vec* a, Vec* b, Vec* c) {}
STUB s32 THPDec_8032F8D4(u8* data, THPDec_8032FD40_Data* out) { return (s32) 0; }
STUB s32 THPDec_8032FD40(THPDec_8032FD40_Data* arg0, u16 arg1) { return (s32) 0; }
STUB void THPDec_80331340(s32, void*, void*, void*) {}
STUB void THPDec_803313D0(s32, void*, void*, void*, u32) {}
STUB void THPInit(void) {}
STUB s32 THPVideoDecode(void* file, void* tileY, void* tileU, void* tileV, void* work) { return (s32) 0; }
STUB void VIConfigure(GXRenderModeObj* rm) {}
STUB void VIFlush(void) {}
STUB u32 VIGetDTVStatus(void) { return (u32) 0; }
STUB u32 VIGetNextField(void) { return (u32) 0; }
STUB u32 VIGetRetraceCount(void) { return (u32) 0; }
STUB u32 VIGetTvFormat(void) { return (u32) 0; }
STUB void VIInit(void) {}
STUB void VISetBlack(BOOL black) {}
STUB void VISetNextFrameBuffer(void* fb) {}
STUB VIRetraceCallback VISetPostRetraceCallback(VIRetraceCallback cb) { return (VIRetraceCallback) 0; }
STUB VIRetraceCallback VISetPreRetraceCallback(VIRetraceCallback cb) { return (VIRetraceCallback) 0; }
STUB void VIWaitForRetrace(void) {}

// No prototype found (handle by hand):
//   GXNtsc480Int
//   GXNtsc480IntDf
//   GXNtsc480Prog
//   MSL_TrigF_80400770
//   MSL_TrigF_80400774
//   PSMTXTrans
//   __OSCurrHeap
//   _stack_addr
//   _stack_end
