// Generated by port/tools/gen_swap.py from the port build's DWARF.
// Do not edit; hand-written swaps live in port/src/swap_port.c.

#include <port/endian.h>

/* HSD_WObjDesc: 0x14 bytes */
void port_swap_HSD_WObjDesc(void* p)
{
    port_swap32((u8*) p + 0x4); /* HSD_WObjDesc.pos.x */
    port_swap32((u8*) p + 0x8); /* HSD_WObjDesc.pos.y */
    port_swap32((u8*) p + 0xC); /* HSD_WObjDesc.pos.z */
}

/* HSD_CameraDescCommon: 0x30 bytes */
void port_swap_HSD_CameraDescCommon(void* p)
{
    port_swap16((u8*) p + 0x4); /* HSD_CameraDescCommon.flags */
    port_swap16((u8*) p + 0x6); /* HSD_CameraDescCommon.projection_type */
    port_swap16((u8*) p + 0x8); /* HSD_CameraDescCommon.viewport.xmin */
    port_swap16((u8*) p + 0xA); /* HSD_CameraDescCommon.viewport.xmax */
    port_swap16((u8*) p + 0xC); /* HSD_CameraDescCommon.viewport.ymin */
    port_swap16((u8*) p + 0xE); /* HSD_CameraDescCommon.viewport.ymax */
    port_swap16((u8*) p + 0x10); /* HSD_CameraDescCommon.scissor.left */
    port_swap16((u8*) p + 0x12); /* HSD_CameraDescCommon.scissor.right */
    port_swap16((u8*) p + 0x14); /* HSD_CameraDescCommon.scissor.top */
    port_swap16((u8*) p + 0x16); /* HSD_CameraDescCommon.scissor.bottom */
    port_swap32((u8*) p + 0x20); /* HSD_CameraDescCommon.roll */
    port_swap32((u8*) p + 0x28); /* HSD_CameraDescCommon.nnear */
    port_swap32((u8*) p + 0x2C); /* HSD_CameraDescCommon.ffar */
}

/* HSD_CameraDescFrustum: 0x40 bytes */
void port_swap_HSD_CameraDescFrustum(void* p)
{
    port_swap16((u8*) p + 0x4); /* HSD_CameraDescFrustum.flags */
    port_swap16((u8*) p + 0x6); /* HSD_CameraDescFrustum.projection_type */
    port_swap16((u8*) p + 0x8); /* HSD_CameraDescFrustum.viewport.xmin */
    port_swap16((u8*) p + 0xA); /* HSD_CameraDescFrustum.viewport.xmax */
    port_swap16((u8*) p + 0xC); /* HSD_CameraDescFrustum.viewport.ymin */
    port_swap16((u8*) p + 0xE); /* HSD_CameraDescFrustum.viewport.ymax */
    port_swap16((u8*) p + 0x10); /* HSD_CameraDescFrustum.scissor.left */
    port_swap16((u8*) p + 0x12); /* HSD_CameraDescFrustum.scissor.right */
    port_swap16((u8*) p + 0x14); /* HSD_CameraDescFrustum.scissor.top */
    port_swap16((u8*) p + 0x16); /* HSD_CameraDescFrustum.scissor.bottom */
    port_swap32((u8*) p + 0x20); /* HSD_CameraDescFrustum.roll */
    port_swap32((u8*) p + 0x28); /* HSD_CameraDescFrustum.nnear */
    port_swap32((u8*) p + 0x2C); /* HSD_CameraDescFrustum.ffar */
    port_swap32((u8*) p + 0x30); /* HSD_CameraDescFrustum.top */
    port_swap32((u8*) p + 0x34); /* HSD_CameraDescFrustum.bottom */
    port_swap32((u8*) p + 0x38); /* HSD_CameraDescFrustum.left */
    port_swap32((u8*) p + 0x3C); /* HSD_CameraDescFrustum.right */
}

/* HSD_CameraDescPerspective: 0x38 bytes */
void port_swap_HSD_CameraDescPerspective(void* p)
{
    port_swap16((u8*) p + 0x4); /* HSD_CameraDescPerspective.flags */
    port_swap16((u8*) p + 0x6); /* HSD_CameraDescPerspective.projection_type */
    port_swap16((u8*) p + 0x8); /* HSD_CameraDescPerspective.viewport.xmin */
    port_swap16((u8*) p + 0xA); /* HSD_CameraDescPerspective.viewport.xmax */
    port_swap16((u8*) p + 0xC); /* HSD_CameraDescPerspective.viewport.ymin */
    port_swap16((u8*) p + 0xE); /* HSD_CameraDescPerspective.viewport.ymax */
    port_swap16((u8*) p + 0x10); /* HSD_CameraDescPerspective.scissor.left */
    port_swap16((u8*) p + 0x12); /* HSD_CameraDescPerspective.scissor.right */
    port_swap16((u8*) p + 0x14); /* HSD_CameraDescPerspective.scissor.top */
    port_swap16((u8*) p + 0x16); /* HSD_CameraDescPerspective.scissor.bottom */
    port_swap32((u8*) p + 0x20); /* HSD_CameraDescPerspective.roll */
    port_swap32((u8*) p + 0x28); /* HSD_CameraDescPerspective.nnear */
    port_swap32((u8*) p + 0x2C); /* HSD_CameraDescPerspective.ffar */
    port_swap32((u8*) p + 0x30); /* HSD_CameraDescPerspective.fov */
    port_swap32((u8*) p + 0x34); /* HSD_CameraDescPerspective.aspect */
}

/* HSD_Joint: 0x40 bytes */
void port_swap_HSD_Joint(void* p)
{
    port_swap32((u8*) p + 0x4); /* HSD_Joint.flags */
    port_swap32((u8*) p + 0x14); /* HSD_Joint.rotation.x */
    port_swap32((u8*) p + 0x18); /* HSD_Joint.rotation.y */
    port_swap32((u8*) p + 0x1C); /* HSD_Joint.rotation.z */
    port_swap32((u8*) p + 0x20); /* HSD_Joint.scale.x */
    port_swap32((u8*) p + 0x24); /* HSD_Joint.scale.y */
    port_swap32((u8*) p + 0x28); /* HSD_Joint.scale.z */
    port_swap32((u8*) p + 0x2C); /* HSD_Joint.position.x */
    port_swap32((u8*) p + 0x30); /* HSD_Joint.position.y */
    port_swap32((u8*) p + 0x34); /* HSD_Joint.position.z */
}

/* HSD_DObjDesc: 0x10 bytes */
void port_swap_HSD_DObjDesc(void* p)
{
}

/* HSD_MObjDesc: 0x18 bytes */
void port_swap_HSD_MObjDesc(void* p)
{
    port_swap32((u8*) p + 0x4); /* HSD_MObjDesc.rendermode */
}

/* HSD_Material: 0x14 bytes */
void port_swap_HSD_Material(void* p)
{
    port_swap32((u8*) p + 0xC); /* HSD_Material.alpha */
    port_swap32((u8*) p + 0x10); /* HSD_Material.shininess */
}

/* HSD_PEDesc: 0xC bytes */
void port_swap_HSD_PEDesc(void* p)
{
}

/* HSD_TObjDesc: 0x5C bytes */
void port_swap_HSD_TObjDesc(void* p)
{
    port_swap32((u8*) p + 0x8); /* HSD_TObjDesc.id */
    port_swap32((u8*) p + 0xC); /* HSD_TObjDesc.src */
    port_swap32((u8*) p + 0x10); /* HSD_TObjDesc.rotate.x */
    port_swap32((u8*) p + 0x14); /* HSD_TObjDesc.rotate.y */
    port_swap32((u8*) p + 0x18); /* HSD_TObjDesc.rotate.z */
    port_swap32((u8*) p + 0x1C); /* HSD_TObjDesc.scale.x */
    port_swap32((u8*) p + 0x20); /* HSD_TObjDesc.scale.y */
    port_swap32((u8*) p + 0x24); /* HSD_TObjDesc.scale.z */
    port_swap32((u8*) p + 0x28); /* HSD_TObjDesc.translate.x */
    port_swap32((u8*) p + 0x2C); /* HSD_TObjDesc.translate.y */
    port_swap32((u8*) p + 0x30); /* HSD_TObjDesc.translate.z */
    port_swap32((u8*) p + 0x34); /* HSD_TObjDesc.wrap_s */
    port_swap32((u8*) p + 0x38); /* HSD_TObjDesc.wrap_t */
    port_swap32((u8*) p + 0x40); /* HSD_TObjDesc.blend_flags */
    port_swap32((u8*) p + 0x44); /* HSD_TObjDesc.blending */
    port_swap32((u8*) p + 0x48); /* HSD_TObjDesc.magFilt */
}

/* HSD_ImageDesc: 0x18 bytes */
void port_swap_HSD_ImageDesc(void* p)
{
    port_swap16((u8*) p + 0x4); /* HSD_ImageDesc.width */
    port_swap16((u8*) p + 0x6); /* HSD_ImageDesc.height */
    port_swap32((u8*) p + 0x8); /* HSD_ImageDesc.format */
    port_swap32((u8*) p + 0xC); /* HSD_ImageDesc.mipmap */
    port_swap32((u8*) p + 0x10); /* HSD_ImageDesc.minLOD */
    port_swap32((u8*) p + 0x14); /* HSD_ImageDesc.maxLOD */
}

/* HSD_TlutDesc: 0x10 bytes */
void port_swap_HSD_TlutDesc(void* p)
{
    port_swap32((u8*) p + 0x4); /* HSD_TlutDesc.fmt */
    port_swap32((u8*) p + 0x8); /* HSD_TlutDesc.tlut_name */
    port_swap16((u8*) p + 0xC); /* HSD_TlutDesc.n_entries */
}

/* HSD_TObjTevDesc: 0x20 bytes */
void port_swap_HSD_TObjTevDesc(void* p)
{
    port_swap32((u8*) p + 0x1C); /* HSD_TObjTevDesc.active */
}

/* HSD_PObjDesc: 0x18 bytes */
void port_swap_HSD_PObjDesc(void* p)
{
    port_swap16((u8*) p + 0xC); /* HSD_PObjDesc.flags */
    port_swap16((u8*) p + 0xE); /* HSD_PObjDesc.n_display */
}

/* HSD_ShapeSetDesc: 0x1C bytes */
void port_swap_HSD_ShapeSetDesc(void* p)
{
    port_swap16((u8*) p + 0x0); /* HSD_ShapeSetDesc.flags */
    port_swap16((u8*) p + 0x2); /* HSD_ShapeSetDesc.nb_shape */
    port_swap32((u8*) p + 0x4); /* HSD_ShapeSetDesc.nb_vertex_index */
    port_swap32((u8*) p + 0x10); /* HSD_ShapeSetDesc.nb_normal_index */
}

/* HSD_ShapeAnim: 0x8 bytes */
void port_swap_HSD_ShapeAnim(void* p)
{
}

/* HSD_ShapeAnimJoint: 0xC bytes */
void port_swap_HSD_ShapeAnimJoint(void* p)
{
}

/* HSD_ShapeAnimDObj: 0x8 bytes */
void port_swap_HSD_ShapeAnimDObj(void* p)
{
}

/* HSD_EnvelopeDesc: 0x8 bytes */
void port_swap_HSD_EnvelopeDesc(void* p)
{
    port_swap32((u8*) p + 0x4); /* HSD_EnvelopeDesc.weight */
}

/* HSD_VtxDescList: 0x18 bytes */
void port_swap_HSD_VtxDescList(void* p)
{
    port_swap32((u8*) p + 0x0); /* HSD_VtxDescList.attr */
    port_swap32((u8*) p + 0x4); /* HSD_VtxDescList.attr_type */
    port_swap32((u8*) p + 0x8); /* HSD_VtxDescList.comp_cnt */
    port_swap32((u8*) p + 0xC); /* HSD_VtxDescList.comp_type */
    port_swap16((u8*) p + 0x12); /* HSD_VtxDescList.stride */
}

/* HSD_AObjDesc: 0x10 bytes */
void port_swap_HSD_AObjDesc(void* p)
{
    port_swap32((u8*) p + 0x0); /* HSD_AObjDesc.flags */
    port_swap32((u8*) p + 0x4); /* HSD_AObjDesc.end_frame */
    port_swap32((u8*) p + 0xC); /* HSD_AObjDesc.obj_id */
}

/* HSD_FObjDesc: 0x14 bytes */
void port_swap_HSD_FObjDesc(void* p)
{
    port_swap32((u8*) p + 0x4); /* HSD_FObjDesc.length */
    port_swap32((u8*) p + 0x8); /* HSD_FObjDesc.startframe */
}

/* HSD_AnimJoint: 0x14 bytes */
void port_swap_HSD_AnimJoint(void* p)
{
    port_swap32((u8*) p + 0x10); /* HSD_AnimJoint.flags */
}

/* HSD_MatAnimJoint: 0xC bytes */
void port_swap_HSD_MatAnimJoint(void* p)
{
}

/* HSD_MatAnim: 0x10 bytes */
void port_swap_HSD_MatAnim(void* p)
{
}

/* HSD_TexAnim: 0x18 bytes */
void port_swap_HSD_TexAnim(void* p)
{
    port_swap32((u8*) p + 0x4); /* HSD_TexAnim.id */
    port_swap16((u8*) p + 0x14); /* HSD_TexAnim.n_imagetbl */
    port_swap16((u8*) p + 0x16); /* HSD_TexAnim.n_tluttbl */
}

/* HSD_LightDesc: 0x1C bytes */
void port_swap_HSD_LightDesc(void* p)
{
    port_swap16((u8*) p + 0x8); /* HSD_LightDesc.flags */
    port_swap16((u8*) p + 0xA); /* HSD_LightDesc.attnflags */
}

/* HSD_LightPoint: 0x14 bytes */
void port_swap_HSD_LightPoint(void* p)
{
    port_swap32((u8*) p + 0x0); /* HSD_LightPoint.cutoff */
    port_swap32((u8*) p + 0x4); /* HSD_LightPoint.point_func */
    port_swap32((u8*) p + 0x8); /* HSD_LightPoint.ref_br */
    port_swap32((u8*) p + 0xC); /* HSD_LightPoint.ref_dist */
    port_swap32((u8*) p + 0x10); /* HSD_LightPoint.dist_func */
}

/* HSD_LightSpot: 0x14 bytes */
void port_swap_HSD_LightSpot(void* p)
{
    port_swap32((u8*) p + 0x0); /* HSD_LightSpot.cutoff */
    port_swap32((u8*) p + 0x4); /* HSD_LightSpot.spot_func */
    port_swap32((u8*) p + 0x8); /* HSD_LightSpot.ref_br */
    port_swap32((u8*) p + 0xC); /* HSD_LightSpot.ref_dist */
    port_swap32((u8*) p + 0x10); /* HSD_LightSpot.dist_func */
}

/* HSD_LightAttn: 0x18 bytes */
void port_swap_HSD_LightAttn(void* p)
{
    port_swap32((u8*) p + 0x0); /* HSD_LightAttn.a0 */
    port_swap32((u8*) p + 0x4); /* HSD_LightAttn.a1 */
    port_swap32((u8*) p + 0x8); /* HSD_LightAttn.a2 */
    port_swap32((u8*) p + 0xC); /* HSD_LightAttn.k0 */
    port_swap32((u8*) p + 0x10); /* HSD_LightAttn.k1 */
    port_swap32((u8*) p + 0x14); /* HSD_LightAttn.k2 */
}

/* HSD_LightAnim: 0x10 bytes */
void port_swap_HSD_LightAnim(void* p)
{
}

/* HSD_FogDesc: 0x14 bytes */
void port_swap_HSD_FogDesc(void* p)
{
    port_swap32((u8*) p + 0x0); /* HSD_FogDesc.type */
    port_swap32((u8*) p + 0x8); /* HSD_FogDesc.start */
    port_swap32((u8*) p + 0xC); /* HSD_FogDesc.end */
}

/* HSD_FogAdjDesc: 0x44 bytes */
void port_swap_HSD_FogAdjDesc(void* p)
{
    port_swap16((u8*) p + 0x0); /* HSD_FogAdjDesc.center */
    port_swap16((u8*) p + 0x2); /* HSD_FogAdjDesc.width */
    port_swap32((u8*) p + 0x4); /* HSD_FogAdjDesc.mtx[0] */
    port_swap32((u8*) p + 0x8); /* HSD_FogAdjDesc.mtx[1] */
    port_swap32((u8*) p + 0xC); /* HSD_FogAdjDesc.mtx[2] */
    port_swap32((u8*) p + 0x10); /* HSD_FogAdjDesc.mtx[3] */
    port_swap32((u8*) p + 0x14); /* HSD_FogAdjDesc.mtx[4] */
    port_swap32((u8*) p + 0x18); /* HSD_FogAdjDesc.mtx[5] */
    port_swap32((u8*) p + 0x1C); /* HSD_FogAdjDesc.mtx[6] */
    port_swap32((u8*) p + 0x20); /* HSD_FogAdjDesc.mtx[7] */
    port_swap32((u8*) p + 0x24); /* HSD_FogAdjDesc.mtx[8] */
    port_swap32((u8*) p + 0x28); /* HSD_FogAdjDesc.mtx[9] */
    port_swap32((u8*) p + 0x2C); /* HSD_FogAdjDesc.mtx[10] */
    port_swap32((u8*) p + 0x30); /* HSD_FogAdjDesc.mtx[11] */
    port_swap32((u8*) p + 0x34); /* HSD_FogAdjDesc.mtx[12] */
    port_swap32((u8*) p + 0x38); /* HSD_FogAdjDesc.mtx[13] */
    port_swap32((u8*) p + 0x3C); /* HSD_FogAdjDesc.mtx[14] */
    port_swap32((u8*) p + 0x40); /* HSD_FogAdjDesc.mtx[15] */
}

/* HSD_RObjDesc: 0xC bytes */
void port_swap_HSD_RObjDesc(void* p)
{
    port_swap32((u8*) p + 0x4); /* HSD_RObjDesc.flags */
    /* NOT SWAPPED: HSD_RObjDesc.u: union */
}

/* HSD_RObjAnimJoint: 0x8 bytes */
void port_swap_HSD_RObjAnimJoint(void* p)
{
}

/* HSD_CameraAnim: 0xC bytes */
void port_swap_HSD_CameraAnim(void* p)
{
}

/* HSD_WObjAnim: 0x8 bytes */
void port_swap_HSD_WObjAnim(void* p)
{
}

/* HSD_ExpDesc: 0x8 bytes */
void port_swap_HSD_ExpDesc(void* p)
{
}

/* HSD_ByteCodeExpDesc: 0x8 bytes */
void port_swap_HSD_ByteCodeExpDesc(void* p)
{
}

/* HSD_RvalueList: 0x8 bytes */
void port_swap_HSD_RvalueList(void* p)
{
    port_swap32((u8*) p + 0x0); /* HSD_RvalueList.flags */
}

/* HSD_LightPointDesc: 0xC bytes */
void port_swap_HSD_LightPointDesc(void* p)
{
    port_swap32((u8*) p + 0x0); /* HSD_LightPointDesc.ref_br */
    port_swap32((u8*) p + 0x4); /* HSD_LightPointDesc.ref_dist */
    port_swap32((u8*) p + 0x8); /* HSD_LightPointDesc.dist_func */
}

/* HSD_LightSpotDesc: 0x14 bytes */
void port_swap_HSD_LightSpotDesc(void* p)
{
    port_swap32((u8*) p + 0x0); /* HSD_LightSpotDesc.cutoff */
    port_swap32((u8*) p + 0x4); /* HSD_LightSpotDesc.spot_func */
    port_swap32((u8*) p + 0x8); /* HSD_LightSpotDesc.ref_br */
    port_swap32((u8*) p + 0xC); /* HSD_LightSpotDesc.ref_dist */
    port_swap32((u8*) p + 0x10); /* HSD_LightSpotDesc.dist_func */
}

/* HSD_TexLODDesc: 0x10 bytes */
void port_swap_HSD_TexLODDesc(void* p)
{
    port_swap32((u8*) p + 0x0); /* HSD_TexLODDesc.minFilt */
    port_swap32((u8*) p + 0x4); /* HSD_TexLODDesc.LODBias */
    port_swap32((u8*) p + 0xC); /* HSD_TexLODDesc.max_anisotropy */
}

/* HSD_Spline: 0x18 bytes */
void port_swap_HSD_Spline(void* p)
{
    port_swap16((u8*) p + 0x2); /* HSD_Spline.numcv */
    port_swap32((u8*) p + 0x4); /* HSD_Spline.tension */
    port_swap32((u8*) p + 0xC); /* HSD_Spline.totalLength */
}

/* GroundParam: 0xDC bytes */
void port_swap_GroundParam(void* p)
{
    port_swap32((u8*) p + 0x0); /* GroundParam.y */
    port_swap16((u8*) p + 0x4); /* GroundParam.x4 */
    port_swap16((u8*) p + 0x8); /* GroundParam.x8 */
    port_swap16((u8*) p + 0xA); /* GroundParam.xA */
    port_swap32((u8*) p + 0xC); /* GroundParam.xC */
    port_swap32((u8*) p + 0x10); /* GroundParam.x10 */
    port_swap32((u8*) p + 0x14); /* GroundParam.x14 */
    port_swap32((u8*) p + 0x18); /* GroundParam.x18 */
    port_swap32((u8*) p + 0x1C); /* GroundParam.x1C */
    port_swap32((u8*) p + 0x20); /* GroundParam.x20 */
    port_swap32((u8*) p + 0x24); /* GroundParam.x24 */
    port_swap32((u8*) p + 0x28); /* GroundParam.x28 */
    port_swap16((u8*) p + 0x2E); /* GroundParam.x2E */
    port_swap32((u8*) p + 0x30); /* GroundParam.x30 */
    port_swap32((u8*) p + 0x34); /* GroundParam.x34 */
    port_swap32((u8*) p + 0x38); /* GroundParam.x38 */
    port_swap32((u8*) p + 0x3C); /* GroundParam.x3C */
    port_swap32((u8*) p + 0x40); /* GroundParam.x40 */
    port_swap32((u8*) p + 0x44); /* GroundParam.x44 */
    port_swap32((u8*) p + 0x48); /* GroundParam.x48 */
    port_swap32((u8*) p + 0x4C); /* GroundParam.x4C_fixed_cam */
    port_swap32((u8*) p + 0x50); /* GroundParam.x50 */
    port_swap32((u8*) p + 0x54); /* GroundParam.x54 */
    port_swap32((u8*) p + 0x58); /* GroundParam.x58 */
    port_swap32((u8*) p + 0x5C); /* GroundParam.x5C */
    port_swap32((u8*) p + 0x60); /* GroundParam.x60 */
    port_swap32((u8*) p + 0x64); /* GroundParam.x64 */
    port_swap16((u8*) p + 0x68); /* GroundParam.x68 */
    port_swap16((u8*) p + 0x6A); /* GroundParam.x6A[0] */
    port_swap16((u8*) p + 0x6C); /* GroundParam.x6A[1] */
    port_swap16((u8*) p + 0x6E); /* GroundParam.x6A[2] */
    port_swap16((u8*) p + 0x70); /* GroundParam.x6A[3] */
    port_swap16((u8*) p + 0x72); /* GroundParam.x6A[4] */
    port_swap16((u8*) p + 0x74); /* GroundParam.x6A[5] */
    port_swap16((u8*) p + 0x76); /* GroundParam.x6A[6] */
    port_swap16((u8*) p + 0x78); /* GroundParam.x6A[7] */
    port_swap16((u8*) p + 0x7A); /* GroundParam.x6A[8] */
    port_swap16((u8*) p + 0x7C); /* GroundParam.x6A[9] */
    port_swap16((u8*) p + 0x7E); /* GroundParam.x6A[10] */
    port_swap16((u8*) p + 0x80); /* GroundParam.x6A[11] */
    port_swap16((u8*) p + 0x82); /* GroundParam.x6A[12] */
    port_swap16((u8*) p + 0x84); /* GroundParam.x6A[13] */
    port_swap16((u8*) p + 0x86); /* GroundParam.x6A[14] */
    port_swap16((u8*) p + 0x88); /* GroundParam.x6A[15] */
    port_swap16((u8*) p + 0x8A); /* GroundParam.x6A[16] */
    port_swap16((u8*) p + 0x8C); /* GroundParam.x6A[17] */
    port_swap16((u8*) p + 0x8E); /* GroundParam.x6A[18] */
    port_swap16((u8*) p + 0x90); /* GroundParam.x6A[19] */
    port_swap16((u8*) p + 0x92); /* GroundParam.x6A[20] */
    port_swap16((u8*) p + 0x94); /* GroundParam.x6A[21] */
    port_swap16((u8*) p + 0x96); /* GroundParam.x6A[22] */
    port_swap16((u8*) p + 0x98); /* GroundParam.x6A[23] */
    port_swap16((u8*) p + 0x9A); /* GroundParam.x6A[24] */
    port_swap16((u8*) p + 0x9C); /* GroundParam.x6A[25] */
    port_swap16((u8*) p + 0x9E); /* GroundParam.x6A[26] */
    port_swap16((u8*) p + 0xA0); /* GroundParam.x6A[27] */
    port_swap16((u8*) p + 0xA2); /* GroundParam.x6A[28] */
    port_swap16((u8*) p + 0xA4); /* GroundParam.x6A[29] */
    port_swap16((u8*) p + 0xA6); /* GroundParam.x6A[30] */
    port_swap16((u8*) p + 0xA8); /* GroundParam.x6A[31] */
    port_swap16((u8*) p + 0xAA); /* GroundParam.x6A[32] */
    port_swap16((u8*) p + 0xAC); /* GroundParam.x6A[33] */
    port_swap16((u8*) p + 0xAE); /* GroundParam.x6A[34] */
    port_swap32((u8*) p + 0xB4); /* GroundParam.stage_param_count */
}

/* StageParam: 0x64 bytes */
void port_swap_StageParam(void* p)
{
    port_swap32((u8*) p + 0x0); /* StageParam.stkind */
    port_swap32((u8*) p + 0x4); /* StageParam.x4 */
    port_swap32((u8*) p + 0x8); /* StageParam.x8 */
    port_swap32((u8*) p + 0xC); /* StageParam.xC */
    port_swap32((u8*) p + 0x10); /* StageParam.x10 */
    port_swap16((u8*) p + 0x14); /* StageParam.x14 */
    port_swap16((u8*) p + 0x16); /* StageParam.x16 */
    port_swap16((u8*) p + 0x18); /* StageParam.x18 */
    port_swap16((u8*) p + 0x1A); /* StageParam.x1A[0] */
    port_swap16((u8*) p + 0x1C); /* StageParam.x1A[1] */
    port_swap16((u8*) p + 0x1E); /* StageParam.x1A[2] */
    port_swap16((u8*) p + 0x20); /* StageParam.x1A[3] */
    port_swap16((u8*) p + 0x22); /* StageParam.x1A[4] */
    port_swap16((u8*) p + 0x24); /* StageParam.x1A[5] */
    port_swap16((u8*) p + 0x26); /* StageParam.x1A[6] */
    port_swap16((u8*) p + 0x28); /* StageParam.x1A[7] */
    port_swap16((u8*) p + 0x2A); /* StageParam.x1A[8] */
    port_swap16((u8*) p + 0x2C); /* StageParam.x1A[9] */
    port_swap16((u8*) p + 0x2E); /* StageParam.x1A[10] */
    port_swap16((u8*) p + 0x30); /* StageParam.x1A[11] */
    port_swap16((u8*) p + 0x32); /* StageParam.x1A[12] */
    port_swap16((u8*) p + 0x34); /* StageParam.x1A[13] */
    port_swap16((u8*) p + 0x36); /* StageParam.x1A[14] */
    port_swap16((u8*) p + 0x38); /* StageParam.x1A[15] */
    port_swap16((u8*) p + 0x3A); /* StageParam.x1A[16] */
    port_swap16((u8*) p + 0x3C); /* StageParam.x1A[17] */
    port_swap16((u8*) p + 0x3E); /* StageParam.x1A[18] */
    port_swap16((u8*) p + 0x40); /* StageParam.x1A[19] */
    port_swap16((u8*) p + 0x42); /* StageParam.x1A[20] */
    port_swap16((u8*) p + 0x44); /* StageParam.x1A[21] */
    port_swap16((u8*) p + 0x46); /* StageParam.x1A[22] */
    port_swap16((u8*) p + 0x48); /* StageParam.x1A[23] */
    port_swap16((u8*) p + 0x4A); /* StageParam.x1A[24] */
    port_swap16((u8*) p + 0x4C); /* StageParam.x1A[25] */
    port_swap16((u8*) p + 0x4E); /* StageParam.x1A[26] */
    port_swap16((u8*) p + 0x50); /* StageParam.x1A[27] */
    port_swap16((u8*) p + 0x52); /* StageParam.x1A[28] */
    port_swap16((u8*) p + 0x54); /* StageParam.x1A[29] */
    port_swap16((u8*) p + 0x56); /* StageParam.x1A[30] */
    port_swap16((u8*) p + 0x58); /* StageParam.x1A[31] */
    port_swap16((u8*) p + 0x5A); /* StageParam.x1A[32] */
    port_swap16((u8*) p + 0x5C); /* StageParam.x1A[33] */
    port_swap16((u8*) p + 0x5E); /* StageParam.x1A[34] */
    port_swap16((u8*) p + 0x60); /* StageParam.x1A[35] */
    port_swap16((u8*) p + 0x62); /* StageParam.x1A[36] */
}

/* MapCollData: 0x30 bytes */
void port_swap_MapCollData(void* p)
{
    port_swap32((u8*) p + 0x4); /* MapCollData.vert_count */
    port_swap32((u8*) p + 0xC); /* MapCollData.line_count */
    port_swap16((u8*) p + 0x10); /* MapCollData.floor_start */
    port_swap16((u8*) p + 0x12); /* MapCollData.floor_count */
    port_swap16((u8*) p + 0x14); /* MapCollData.ceiling_start */
    port_swap16((u8*) p + 0x16); /* MapCollData.ceiling_count */
    port_swap16((u8*) p + 0x18); /* MapCollData.right_wall_start */
    port_swap16((u8*) p + 0x1A); /* MapCollData.right_wall_count */
    port_swap16((u8*) p + 0x1C); /* MapCollData.left_wall_start */
    port_swap16((u8*) p + 0x1E); /* MapCollData.left_wall_count */
    port_swap16((u8*) p + 0x20); /* MapCollData.dynamic_start */
    port_swap16((u8*) p + 0x22); /* MapCollData.dynamic_count */
    port_swap32((u8*) p + 0x28); /* MapCollData.joint_count */
    port_swap32((u8*) p + 0x2C); /* MapCollData.x2C */
}

/* MapLine: 0x10 bytes */
void port_swap_MapLine(void* p)
{
    port_swap16((u8*) p + 0x0); /* MapLine.v0_idx */
    port_swap16((u8*) p + 0x2); /* MapLine.v1_idx */
    port_swap16((u8*) p + 0x4); /* MapLine.prev_id0 */
    port_swap16((u8*) p + 0x6); /* MapLine.next_id0 */
    port_swap16((u8*) p + 0x8); /* MapLine.prev_id1 */
    port_swap16((u8*) p + 0xA); /* MapLine.next_id1 */
    port_swap16((u8*) p + 0xC); /* MapLine.hi_flags */
    port_swap16((u8*) p + 0xE); /* MapLine.lo_flags */
}

/* MapJoint: 0x28 bytes */
void port_swap_MapJoint(void* p)
{
    port_swap16((u8*) p + 0x0); /* MapJoint.floor_start */
    port_swap16((u8*) p + 0x2); /* MapJoint.floor_count */
    port_swap16((u8*) p + 0x4); /* MapJoint.ceiling_start */
    port_swap16((u8*) p + 0x6); /* MapJoint.ceiling_count */
    port_swap16((u8*) p + 0x8); /* MapJoint.right_wall_start */
    port_swap16((u8*) p + 0xA); /* MapJoint.right_wall_count */
    port_swap16((u8*) p + 0xC); /* MapJoint.left_wall_start */
    port_swap16((u8*) p + 0xE); /* MapJoint.left_wall_count */
    port_swap16((u8*) p + 0x10); /* MapJoint.dynamic_start */
    port_swap16((u8*) p + 0x12); /* MapJoint.dynamic_count */
    port_swap32((u8*) p + 0x14); /* MapJoint.left_bound */
    port_swap32((u8*) p + 0x18); /* MapJoint.bottom_bound */
    port_swap32((u8*) p + 0x1C); /* MapJoint.right_bound */
    port_swap32((u8*) p + 0x20); /* MapJoint.top_bound */
    port_swap16((u8*) p + 0x24); /* MapJoint.vtx_start */
    port_swap16((u8*) p + 0x26); /* MapJoint.vtx_count */
}

/* UnkStageDat: 0x30 bytes */
void port_swap_UnkStageDat(void* p)
{
    port_swap32((u8*) p + 0x4); /* UnkStageDat.unk4 */
    port_swap32((u8*) p + 0xC); /* UnkStageDat.unkC */
    port_swap32((u8*) p + 0x14); /* UnkStageDat.unk14 */
    port_swap32((u8*) p + 0x1C); /* UnkStageDat.unk1C */
    port_swap32((u8*) p + 0x24); /* UnkStageDat.unk24 */
    port_swap32((u8*) p + 0x2C); /* UnkStageDat.unk2C */
}

/* UnkStageDat_x8_t: 0x34 bytes */
void port_swap_UnkStageDat_x8_t(void* p)
{
    port_swap32((u8*) p + 0x24); /* UnkStageDat_x8_t.unk24 */
    port_swap32((u8*) p + 0x30); /* UnkStageDat_x8_t.x30 */
}

/* GroundShadowEntry: 0x8 bytes */
void port_swap_GroundShadowEntry(void* p)
{
    if (port_claim((u8*) p + 0x4, 1)) { /* bitfields: GroundShadowEntry.flag */
        u8* b = (u8*) p + 0x4;
        u32 be = ((u32) b[0] << 0);
        u32 host = 0;
        host |= ((be >> 7) & 0x1u) << 0;
        *(u8*) b = (u8) host;
    }
}

/* GrJoint: 0x6 bytes */
void port_swap_GrJoint(void* p)
{
    port_swap16((u8*) p + 0x0); /* GrJoint.x */
    port_swap16((u8*) p + 0x2); /* GrJoint.y */
    port_swap16((u8*) p + 0x4); /* GrJoint.z */
}
