// Generated by port/tools/gen_swap.py from the port build's DWARF.
// Do not edit; hand-written swaps live in port/src/swap_port.c.

#include <port/endian.h>

/* HSD_WObjDesc: 0x14 bytes */
void port_swap_HSD_WObjDesc(void* p)
{
    port_swap32((u8*) p + 0x4); /* HSD_WObjDesc.pos.x */
    port_swap32((u8*) p + 0x8); /* HSD_WObjDesc.pos.y */
    port_swap32((u8*) p + 0xC); /* HSD_WObjDesc.pos.z */
}

/* HSD_CameraDescCommon: 0x30 bytes */
void port_swap_HSD_CameraDescCommon(void* p)
{
    port_swap16((u8*) p + 0x4); /* HSD_CameraDescCommon.flags */
    port_swap16((u8*) p + 0x6); /* HSD_CameraDescCommon.projection_type */
    port_swap16((u8*) p + 0x8); /* HSD_CameraDescCommon.viewport.xmin */
    port_swap16((u8*) p + 0xA); /* HSD_CameraDescCommon.viewport.xmax */
    port_swap16((u8*) p + 0xC); /* HSD_CameraDescCommon.viewport.ymin */
    port_swap16((u8*) p + 0xE); /* HSD_CameraDescCommon.viewport.ymax */
    port_swap16((u8*) p + 0x10); /* HSD_CameraDescCommon.scissor.left */
    port_swap16((u8*) p + 0x12); /* HSD_CameraDescCommon.scissor.right */
    port_swap16((u8*) p + 0x14); /* HSD_CameraDescCommon.scissor.top */
    port_swap16((u8*) p + 0x16); /* HSD_CameraDescCommon.scissor.bottom */
    port_swap32((u8*) p + 0x20); /* HSD_CameraDescCommon.roll */
    port_swap32((u8*) p + 0x28); /* HSD_CameraDescCommon.nnear */
    port_swap32((u8*) p + 0x2C); /* HSD_CameraDescCommon.ffar */
}

/* HSD_CameraDescFrustum: 0x40 bytes */
void port_swap_HSD_CameraDescFrustum(void* p)
{
    port_swap16((u8*) p + 0x4); /* HSD_CameraDescFrustum.flags */
    port_swap16((u8*) p + 0x6); /* HSD_CameraDescFrustum.projection_type */
    port_swap16((u8*) p + 0x8); /* HSD_CameraDescFrustum.viewport.xmin */
    port_swap16((u8*) p + 0xA); /* HSD_CameraDescFrustum.viewport.xmax */
    port_swap16((u8*) p + 0xC); /* HSD_CameraDescFrustum.viewport.ymin */
    port_swap16((u8*) p + 0xE); /* HSD_CameraDescFrustum.viewport.ymax */
    port_swap16((u8*) p + 0x10); /* HSD_CameraDescFrustum.scissor.left */
    port_swap16((u8*) p + 0x12); /* HSD_CameraDescFrustum.scissor.right */
    port_swap16((u8*) p + 0x14); /* HSD_CameraDescFrustum.scissor.top */
    port_swap16((u8*) p + 0x16); /* HSD_CameraDescFrustum.scissor.bottom */
    port_swap32((u8*) p + 0x20); /* HSD_CameraDescFrustum.roll */
    port_swap32((u8*) p + 0x28); /* HSD_CameraDescFrustum.nnear */
    port_swap32((u8*) p + 0x2C); /* HSD_CameraDescFrustum.ffar */
    port_swap32((u8*) p + 0x30); /* HSD_CameraDescFrustum.top */
    port_swap32((u8*) p + 0x34); /* HSD_CameraDescFrustum.bottom */
    port_swap32((u8*) p + 0x38); /* HSD_CameraDescFrustum.left */
    port_swap32((u8*) p + 0x3C); /* HSD_CameraDescFrustum.right */
}

/* HSD_CameraDescPerspective: 0x38 bytes */
void port_swap_HSD_CameraDescPerspective(void* p)
{
    port_swap16((u8*) p + 0x4); /* HSD_CameraDescPerspective.flags */
    port_swap16((u8*) p + 0x6); /* HSD_CameraDescPerspective.projection_type */
    port_swap16((u8*) p + 0x8); /* HSD_CameraDescPerspective.viewport.xmin */
    port_swap16((u8*) p + 0xA); /* HSD_CameraDescPerspective.viewport.xmax */
    port_swap16((u8*) p + 0xC); /* HSD_CameraDescPerspective.viewport.ymin */
    port_swap16((u8*) p + 0xE); /* HSD_CameraDescPerspective.viewport.ymax */
    port_swap16((u8*) p + 0x10); /* HSD_CameraDescPerspective.scissor.left */
    port_swap16((u8*) p + 0x12); /* HSD_CameraDescPerspective.scissor.right */
    port_swap16((u8*) p + 0x14); /* HSD_CameraDescPerspective.scissor.top */
    port_swap16((u8*) p + 0x16); /* HSD_CameraDescPerspective.scissor.bottom */
    port_swap32((u8*) p + 0x20); /* HSD_CameraDescPerspective.roll */
    port_swap32((u8*) p + 0x28); /* HSD_CameraDescPerspective.nnear */
    port_swap32((u8*) p + 0x2C); /* HSD_CameraDescPerspective.ffar */
    port_swap32((u8*) p + 0x30); /* HSD_CameraDescPerspective.fov */
    port_swap32((u8*) p + 0x34); /* HSD_CameraDescPerspective.aspect */
}

/* HSD_Joint: 0x40 bytes */
void port_swap_HSD_Joint(void* p)
{
    port_swap32((u8*) p + 0x4); /* HSD_Joint.flags */
    port_swap32((u8*) p + 0x14); /* HSD_Joint.rotation.x */
    port_swap32((u8*) p + 0x18); /* HSD_Joint.rotation.y */
    port_swap32((u8*) p + 0x1C); /* HSD_Joint.rotation.z */
    port_swap32((u8*) p + 0x20); /* HSD_Joint.scale.x */
    port_swap32((u8*) p + 0x24); /* HSD_Joint.scale.y */
    port_swap32((u8*) p + 0x28); /* HSD_Joint.scale.z */
    port_swap32((u8*) p + 0x2C); /* HSD_Joint.position.x */
    port_swap32((u8*) p + 0x30); /* HSD_Joint.position.y */
    port_swap32((u8*) p + 0x34); /* HSD_Joint.position.z */
}

/* HSD_DObjDesc: 0x10 bytes */
void port_swap_HSD_DObjDesc(void* p)
{
}

/* HSD_MObjDesc: 0x18 bytes */
void port_swap_HSD_MObjDesc(void* p)
{
    port_swap32((u8*) p + 0x4); /* HSD_MObjDesc.rendermode */
}

/* HSD_Material: 0x14 bytes */
void port_swap_HSD_Material(void* p)
{
    port_swap32((u8*) p + 0xC); /* HSD_Material.alpha */
    port_swap32((u8*) p + 0x10); /* HSD_Material.shininess */
}

/* HSD_PEDesc: 0xC bytes */
void port_swap_HSD_PEDesc(void* p)
{
}

/* HSD_TObjDesc: 0x5C bytes */
void port_swap_HSD_TObjDesc(void* p)
{
    port_swap32((u8*) p + 0x8); /* HSD_TObjDesc.id */
    port_swap32((u8*) p + 0xC); /* HSD_TObjDesc.src */
    port_swap32((u8*) p + 0x10); /* HSD_TObjDesc.rotate.x */
    port_swap32((u8*) p + 0x14); /* HSD_TObjDesc.rotate.y */
    port_swap32((u8*) p + 0x18); /* HSD_TObjDesc.rotate.z */
    port_swap32((u8*) p + 0x1C); /* HSD_TObjDesc.scale.x */
    port_swap32((u8*) p + 0x20); /* HSD_TObjDesc.scale.y */
    port_swap32((u8*) p + 0x24); /* HSD_TObjDesc.scale.z */
    port_swap32((u8*) p + 0x28); /* HSD_TObjDesc.translate.x */
    port_swap32((u8*) p + 0x2C); /* HSD_TObjDesc.translate.y */
    port_swap32((u8*) p + 0x30); /* HSD_TObjDesc.translate.z */
    port_swap32((u8*) p + 0x34); /* HSD_TObjDesc.wrap_s */
    port_swap32((u8*) p + 0x38); /* HSD_TObjDesc.wrap_t */
    port_swap32((u8*) p + 0x40); /* HSD_TObjDesc.blend_flags */
    port_swap32((u8*) p + 0x44); /* HSD_TObjDesc.blending */
    port_swap32((u8*) p + 0x48); /* HSD_TObjDesc.magFilt */
}

/* HSD_ImageDesc: 0x18 bytes */
void port_swap_HSD_ImageDesc(void* p)
{
    port_swap16((u8*) p + 0x4); /* HSD_ImageDesc.width */
    port_swap16((u8*) p + 0x6); /* HSD_ImageDesc.height */
    port_swap32((u8*) p + 0x8); /* HSD_ImageDesc.format */
    port_swap32((u8*) p + 0xC); /* HSD_ImageDesc.mipmap */
    port_swap32((u8*) p + 0x10); /* HSD_ImageDesc.minLOD */
    port_swap32((u8*) p + 0x14); /* HSD_ImageDesc.maxLOD */
}

/* HSD_TlutDesc: 0x10 bytes */
void port_swap_HSD_TlutDesc(void* p)
{
    port_swap32((u8*) p + 0x4); /* HSD_TlutDesc.fmt */
    port_swap32((u8*) p + 0x8); /* HSD_TlutDesc.tlut_name */
    port_swap16((u8*) p + 0xC); /* HSD_TlutDesc.n_entries */
}

/* HSD_TObjTevDesc: 0x20 bytes */
void port_swap_HSD_TObjTevDesc(void* p)
{
    port_swap32((u8*) p + 0x1C); /* HSD_TObjTevDesc.active */
}

/* HSD_PObjDesc: 0x18 bytes */
void port_swap_HSD_PObjDesc(void* p)
{
    port_swap16((u8*) p + 0xC); /* HSD_PObjDesc.flags */
    port_swap16((u8*) p + 0xE); /* HSD_PObjDesc.n_display */
}

/* HSD_ShapeSetDesc: 0x1C bytes */
void port_swap_HSD_ShapeSetDesc(void* p)
{
    port_swap16((u8*) p + 0x0); /* HSD_ShapeSetDesc.flags */
    port_swap16((u8*) p + 0x2); /* HSD_ShapeSetDesc.nb_shape */
    port_swap32((u8*) p + 0x4); /* HSD_ShapeSetDesc.nb_vertex_index */
    port_swap32((u8*) p + 0x10); /* HSD_ShapeSetDesc.nb_normal_index */
}

/* HSD_ShapeAnim: 0x8 bytes */
void port_swap_HSD_ShapeAnim(void* p)
{
}

/* HSD_ShapeAnimJoint: 0xC bytes */
void port_swap_HSD_ShapeAnimJoint(void* p)
{
}

/* HSD_ShapeAnimDObj: 0x8 bytes */
void port_swap_HSD_ShapeAnimDObj(void* p)
{
}

/* HSD_EnvelopeDesc: 0x8 bytes */
void port_swap_HSD_EnvelopeDesc(void* p)
{
    port_swap32((u8*) p + 0x4); /* HSD_EnvelopeDesc.weight */
}

/* HSD_VtxDescList: 0x18 bytes */
void port_swap_HSD_VtxDescList(void* p)
{
    port_swap32((u8*) p + 0x0); /* HSD_VtxDescList.attr */
    port_swap32((u8*) p + 0x4); /* HSD_VtxDescList.attr_type */
    port_swap32((u8*) p + 0x8); /* HSD_VtxDescList.comp_cnt */
    port_swap32((u8*) p + 0xC); /* HSD_VtxDescList.comp_type */
    port_swap16((u8*) p + 0x12); /* HSD_VtxDescList.stride */
}

/* HSD_AObjDesc: 0x10 bytes */
void port_swap_HSD_AObjDesc(void* p)
{
    port_swap32((u8*) p + 0x0); /* HSD_AObjDesc.flags */
    port_swap32((u8*) p + 0x4); /* HSD_AObjDesc.end_frame */
    port_swap32((u8*) p + 0xC); /* HSD_AObjDesc.obj_id */
}

/* HSD_FObjDesc: 0x14 bytes */
void port_swap_HSD_FObjDesc(void* p)
{
    port_swap32((u8*) p + 0x4); /* HSD_FObjDesc.length */
    port_swap32((u8*) p + 0x8); /* HSD_FObjDesc.startframe */
}

/* HSD_AnimJoint: 0x14 bytes */
void port_swap_HSD_AnimJoint(void* p)
{
    port_swap32((u8*) p + 0x10); /* HSD_AnimJoint.flags */
}

/* HSD_MatAnimJoint: 0xC bytes */
void port_swap_HSD_MatAnimJoint(void* p)
{
}

/* HSD_MatAnim: 0x10 bytes */
void port_swap_HSD_MatAnim(void* p)
{
}

/* HSD_TexAnim: 0x18 bytes */
void port_swap_HSD_TexAnim(void* p)
{
    port_swap32((u8*) p + 0x4); /* HSD_TexAnim.id */
    port_swap16((u8*) p + 0x14); /* HSD_TexAnim.n_imagetbl */
    port_swap16((u8*) p + 0x16); /* HSD_TexAnim.n_tluttbl */
}

/* HSD_LightDesc: 0x1C bytes */
void port_swap_HSD_LightDesc(void* p)
{
    port_swap16((u8*) p + 0x8); /* HSD_LightDesc.flags */
    port_swap16((u8*) p + 0xA); /* HSD_LightDesc.attnflags */
}

/* HSD_LightPoint: 0x14 bytes */
void port_swap_HSD_LightPoint(void* p)
{
    port_swap32((u8*) p + 0x0); /* HSD_LightPoint.cutoff */
    port_swap32((u8*) p + 0x4); /* HSD_LightPoint.point_func */
    port_swap32((u8*) p + 0x8); /* HSD_LightPoint.ref_br */
    port_swap32((u8*) p + 0xC); /* HSD_LightPoint.ref_dist */
    port_swap32((u8*) p + 0x10); /* HSD_LightPoint.dist_func */
}

/* HSD_LightSpot: 0x14 bytes */
void port_swap_HSD_LightSpot(void* p)
{
    port_swap32((u8*) p + 0x0); /* HSD_LightSpot.cutoff */
    port_swap32((u8*) p + 0x4); /* HSD_LightSpot.spot_func */
    port_swap32((u8*) p + 0x8); /* HSD_LightSpot.ref_br */
    port_swap32((u8*) p + 0xC); /* HSD_LightSpot.ref_dist */
    port_swap32((u8*) p + 0x10); /* HSD_LightSpot.dist_func */
}

/* HSD_LightAttn: 0x18 bytes */
void port_swap_HSD_LightAttn(void* p)
{
    port_swap32((u8*) p + 0x0); /* HSD_LightAttn.a0 */
    port_swap32((u8*) p + 0x4); /* HSD_LightAttn.a1 */
    port_swap32((u8*) p + 0x8); /* HSD_LightAttn.a2 */
    port_swap32((u8*) p + 0xC); /* HSD_LightAttn.k0 */
    port_swap32((u8*) p + 0x10); /* HSD_LightAttn.k1 */
    port_swap32((u8*) p + 0x14); /* HSD_LightAttn.k2 */
}

/* HSD_LightAnim: 0x10 bytes */
void port_swap_HSD_LightAnim(void* p)
{
}

/* HSD_FogDesc: 0x14 bytes */
void port_swap_HSD_FogDesc(void* p)
{
    port_swap32((u8*) p + 0x0); /* HSD_FogDesc.type */
    port_swap32((u8*) p + 0x8); /* HSD_FogDesc.start */
    port_swap32((u8*) p + 0xC); /* HSD_FogDesc.end */
}

/* HSD_FogAdjDesc: 0x44 bytes */
void port_swap_HSD_FogAdjDesc(void* p)
{
    port_swap16((u8*) p + 0x0); /* HSD_FogAdjDesc.center */
    port_swap16((u8*) p + 0x2); /* HSD_FogAdjDesc.width */
    port_swap32((u8*) p + 0x4); /* HSD_FogAdjDesc.mtx[0] */
    port_swap32((u8*) p + 0x8); /* HSD_FogAdjDesc.mtx[1] */
    port_swap32((u8*) p + 0xC); /* HSD_FogAdjDesc.mtx[2] */
    port_swap32((u8*) p + 0x10); /* HSD_FogAdjDesc.mtx[3] */
    port_swap32((u8*) p + 0x14); /* HSD_FogAdjDesc.mtx[4] */
    port_swap32((u8*) p + 0x18); /* HSD_FogAdjDesc.mtx[5] */
    port_swap32((u8*) p + 0x1C); /* HSD_FogAdjDesc.mtx[6] */
    port_swap32((u8*) p + 0x20); /* HSD_FogAdjDesc.mtx[7] */
    port_swap32((u8*) p + 0x24); /* HSD_FogAdjDesc.mtx[8] */
    port_swap32((u8*) p + 0x28); /* HSD_FogAdjDesc.mtx[9] */
    port_swap32((u8*) p + 0x2C); /* HSD_FogAdjDesc.mtx[10] */
    port_swap32((u8*) p + 0x30); /* HSD_FogAdjDesc.mtx[11] */
    port_swap32((u8*) p + 0x34); /* HSD_FogAdjDesc.mtx[12] */
    port_swap32((u8*) p + 0x38); /* HSD_FogAdjDesc.mtx[13] */
    port_swap32((u8*) p + 0x3C); /* HSD_FogAdjDesc.mtx[14] */
    port_swap32((u8*) p + 0x40); /* HSD_FogAdjDesc.mtx[15] */
}

/* HSD_RObjDesc: 0xC bytes */
void port_swap_HSD_RObjDesc(void* p)
{
    port_swap32((u8*) p + 0x4); /* HSD_RObjDesc.flags */
    /* NOT SWAPPED: HSD_RObjDesc.u: union */
}

/* HSD_RObjAnimJoint: 0x8 bytes */
void port_swap_HSD_RObjAnimJoint(void* p)
{
}

/* HSD_CameraAnim: 0xC bytes */
void port_swap_HSD_CameraAnim(void* p)
{
}

/* HSD_WObjAnim: 0x8 bytes */
void port_swap_HSD_WObjAnim(void* p)
{
}

/* HSD_ExpDesc: 0x8 bytes */
void port_swap_HSD_ExpDesc(void* p)
{
}

/* HSD_ByteCodeExpDesc: 0x8 bytes */
void port_swap_HSD_ByteCodeExpDesc(void* p)
{
}

/* HSD_RvalueList: 0x8 bytes */
void port_swap_HSD_RvalueList(void* p)
{
    port_swap32((u8*) p + 0x0); /* HSD_RvalueList.flags */
}

/* HSD_LightPointDesc: 0xC bytes */
void port_swap_HSD_LightPointDesc(void* p)
{
    port_swap32((u8*) p + 0x0); /* HSD_LightPointDesc.ref_br */
    port_swap32((u8*) p + 0x4); /* HSD_LightPointDesc.ref_dist */
    port_swap32((u8*) p + 0x8); /* HSD_LightPointDesc.dist_func */
}

/* HSD_LightSpotDesc: 0x14 bytes */
void port_swap_HSD_LightSpotDesc(void* p)
{
    port_swap32((u8*) p + 0x0); /* HSD_LightSpotDesc.cutoff */
    port_swap32((u8*) p + 0x4); /* HSD_LightSpotDesc.spot_func */
    port_swap32((u8*) p + 0x8); /* HSD_LightSpotDesc.ref_br */
    port_swap32((u8*) p + 0xC); /* HSD_LightSpotDesc.ref_dist */
    port_swap32((u8*) p + 0x10); /* HSD_LightSpotDesc.dist_func */
}

/* HSD_TexLODDesc: 0x10 bytes */
void port_swap_HSD_TexLODDesc(void* p)
{
    port_swap32((u8*) p + 0x0); /* HSD_TexLODDesc.minFilt */
    port_swap32((u8*) p + 0x4); /* HSD_TexLODDesc.LODBias */
    port_swap32((u8*) p + 0xC); /* HSD_TexLODDesc.max_anisotropy */
}

/* HSD_Spline: 0x18 bytes */
void port_swap_HSD_Spline(void* p)
{
    port_swap16((u8*) p + 0x2); /* HSD_Spline.numcv */
    port_swap32((u8*) p + 0x4); /* HSD_Spline.tension */
    port_swap32((u8*) p + 0xC); /* HSD_Spline.totalLength */
}

/* GroundParam: 0xDC bytes */
void port_swap_GroundParam(void* p)
{
    port_swap32((u8*) p + 0x0); /* GroundParam.y */
    port_swap16((u8*) p + 0x4); /* GroundParam.x4 */
    port_swap16((u8*) p + 0x8); /* GroundParam.x8 */
    port_swap16((u8*) p + 0xA); /* GroundParam.xA */
    port_swap32((u8*) p + 0xC); /* GroundParam.xC */
    port_swap32((u8*) p + 0x10); /* GroundParam.x10 */
    port_swap32((u8*) p + 0x14); /* GroundParam.x14 */
    port_swap32((u8*) p + 0x18); /* GroundParam.x18 */
    port_swap32((u8*) p + 0x1C); /* GroundParam.x1C */
    port_swap32((u8*) p + 0x20); /* GroundParam.x20 */
    port_swap32((u8*) p + 0x24); /* GroundParam.x24 */
    port_swap32((u8*) p + 0x28); /* GroundParam.x28 */
    port_swap16((u8*) p + 0x2E); /* GroundParam.x2E */
    port_swap32((u8*) p + 0x30); /* GroundParam.x30 */
    port_swap32((u8*) p + 0x34); /* GroundParam.x34 */
    port_swap32((u8*) p + 0x38); /* GroundParam.x38 */
    port_swap32((u8*) p + 0x3C); /* GroundParam.x3C */
    port_swap32((u8*) p + 0x40); /* GroundParam.x40 */
    port_swap32((u8*) p + 0x44); /* GroundParam.x44 */
    port_swap32((u8*) p + 0x48); /* GroundParam.x48 */
    port_swap32((u8*) p + 0x4C); /* GroundParam.x4C_fixed_cam */
    port_swap32((u8*) p + 0x50); /* GroundParam.x50 */
    port_swap32((u8*) p + 0x54); /* GroundParam.x54 */
    port_swap32((u8*) p + 0x58); /* GroundParam.x58 */
    port_swap32((u8*) p + 0x5C); /* GroundParam.x5C */
    port_swap32((u8*) p + 0x60); /* GroundParam.x60 */
    port_swap32((u8*) p + 0x64); /* GroundParam.x64 */
    port_swap16((u8*) p + 0x68); /* GroundParam.x68 */
    port_swap16((u8*) p + 0x6A); /* GroundParam.x6A[0] */
    port_swap16((u8*) p + 0x6C); /* GroundParam.x6A[1] */
    port_swap16((u8*) p + 0x6E); /* GroundParam.x6A[2] */
    port_swap16((u8*) p + 0x70); /* GroundParam.x6A[3] */
    port_swap16((u8*) p + 0x72); /* GroundParam.x6A[4] */
    port_swap16((u8*) p + 0x74); /* GroundParam.x6A[5] */
    port_swap16((u8*) p + 0x76); /* GroundParam.x6A[6] */
    port_swap16((u8*) p + 0x78); /* GroundParam.x6A[7] */
    port_swap16((u8*) p + 0x7A); /* GroundParam.x6A[8] */
    port_swap16((u8*) p + 0x7C); /* GroundParam.x6A[9] */
    port_swap16((u8*) p + 0x7E); /* GroundParam.x6A[10] */
    port_swap16((u8*) p + 0x80); /* GroundParam.x6A[11] */
    port_swap16((u8*) p + 0x82); /* GroundParam.x6A[12] */
    port_swap16((u8*) p + 0x84); /* GroundParam.x6A[13] */
    port_swap16((u8*) p + 0x86); /* GroundParam.x6A[14] */
    port_swap16((u8*) p + 0x88); /* GroundParam.x6A[15] */
    port_swap16((u8*) p + 0x8A); /* GroundParam.x6A[16] */
    port_swap16((u8*) p + 0x8C); /* GroundParam.x6A[17] */
    port_swap16((u8*) p + 0x8E); /* GroundParam.x6A[18] */
    port_swap16((u8*) p + 0x90); /* GroundParam.x6A[19] */
    port_swap16((u8*) p + 0x92); /* GroundParam.x6A[20] */
    port_swap16((u8*) p + 0x94); /* GroundParam.x6A[21] */
    port_swap16((u8*) p + 0x96); /* GroundParam.x6A[22] */
    port_swap16((u8*) p + 0x98); /* GroundParam.x6A[23] */
    port_swap16((u8*) p + 0x9A); /* GroundParam.x6A[24] */
    port_swap16((u8*) p + 0x9C); /* GroundParam.x6A[25] */
    port_swap16((u8*) p + 0x9E); /* GroundParam.x6A[26] */
    port_swap16((u8*) p + 0xA0); /* GroundParam.x6A[27] */
    port_swap16((u8*) p + 0xA2); /* GroundParam.x6A[28] */
    port_swap16((u8*) p + 0xA4); /* GroundParam.x6A[29] */
    port_swap16((u8*) p + 0xA6); /* GroundParam.x6A[30] */
    port_swap16((u8*) p + 0xA8); /* GroundParam.x6A[31] */
    port_swap16((u8*) p + 0xAA); /* GroundParam.x6A[32] */
    port_swap16((u8*) p + 0xAC); /* GroundParam.x6A[33] */
    port_swap16((u8*) p + 0xAE); /* GroundParam.x6A[34] */
    port_swap32((u8*) p + 0xB4); /* GroundParam.stage_param_count */
}

/* StageParam: 0x64 bytes */
void port_swap_StageParam(void* p)
{
    port_swap32((u8*) p + 0x0); /* StageParam.stkind */
    port_swap32((u8*) p + 0x4); /* StageParam.x4 */
    port_swap32((u8*) p + 0x8); /* StageParam.x8 */
    port_swap32((u8*) p + 0xC); /* StageParam.xC */
    port_swap32((u8*) p + 0x10); /* StageParam.x10 */
    port_swap16((u8*) p + 0x14); /* StageParam.x14 */
    port_swap16((u8*) p + 0x16); /* StageParam.x16 */
    port_swap16((u8*) p + 0x18); /* StageParam.x18 */
    port_swap16((u8*) p + 0x1A); /* StageParam.x1A[0] */
    port_swap16((u8*) p + 0x1C); /* StageParam.x1A[1] */
    port_swap16((u8*) p + 0x1E); /* StageParam.x1A[2] */
    port_swap16((u8*) p + 0x20); /* StageParam.x1A[3] */
    port_swap16((u8*) p + 0x22); /* StageParam.x1A[4] */
    port_swap16((u8*) p + 0x24); /* StageParam.x1A[5] */
    port_swap16((u8*) p + 0x26); /* StageParam.x1A[6] */
    port_swap16((u8*) p + 0x28); /* StageParam.x1A[7] */
    port_swap16((u8*) p + 0x2A); /* StageParam.x1A[8] */
    port_swap16((u8*) p + 0x2C); /* StageParam.x1A[9] */
    port_swap16((u8*) p + 0x2E); /* StageParam.x1A[10] */
    port_swap16((u8*) p + 0x30); /* StageParam.x1A[11] */
    port_swap16((u8*) p + 0x32); /* StageParam.x1A[12] */
    port_swap16((u8*) p + 0x34); /* StageParam.x1A[13] */
    port_swap16((u8*) p + 0x36); /* StageParam.x1A[14] */
    port_swap16((u8*) p + 0x38); /* StageParam.x1A[15] */
    port_swap16((u8*) p + 0x3A); /* StageParam.x1A[16] */
    port_swap16((u8*) p + 0x3C); /* StageParam.x1A[17] */
    port_swap16((u8*) p + 0x3E); /* StageParam.x1A[18] */
    port_swap16((u8*) p + 0x40); /* StageParam.x1A[19] */
    port_swap16((u8*) p + 0x42); /* StageParam.x1A[20] */
    port_swap16((u8*) p + 0x44); /* StageParam.x1A[21] */
    port_swap16((u8*) p + 0x46); /* StageParam.x1A[22] */
    port_swap16((u8*) p + 0x48); /* StageParam.x1A[23] */
    port_swap16((u8*) p + 0x4A); /* StageParam.x1A[24] */
    port_swap16((u8*) p + 0x4C); /* StageParam.x1A[25] */
    port_swap16((u8*) p + 0x4E); /* StageParam.x1A[26] */
    port_swap16((u8*) p + 0x50); /* StageParam.x1A[27] */
    port_swap16((u8*) p + 0x52); /* StageParam.x1A[28] */
    port_swap16((u8*) p + 0x54); /* StageParam.x1A[29] */
    port_swap16((u8*) p + 0x56); /* StageParam.x1A[30] */
    port_swap16((u8*) p + 0x58); /* StageParam.x1A[31] */
    port_swap16((u8*) p + 0x5A); /* StageParam.x1A[32] */
    port_swap16((u8*) p + 0x5C); /* StageParam.x1A[33] */
    port_swap16((u8*) p + 0x5E); /* StageParam.x1A[34] */
    port_swap16((u8*) p + 0x60); /* StageParam.x1A[35] */
    port_swap16((u8*) p + 0x62); /* StageParam.x1A[36] */
}

/* MapCollData: 0x30 bytes */
void port_swap_MapCollData(void* p)
{
    port_swap32((u8*) p + 0x4); /* MapCollData.vert_count */
    port_swap32((u8*) p + 0xC); /* MapCollData.line_count */
    port_swap16((u8*) p + 0x10); /* MapCollData.floor_start */
    port_swap16((u8*) p + 0x12); /* MapCollData.floor_count */
    port_swap16((u8*) p + 0x14); /* MapCollData.ceiling_start */
    port_swap16((u8*) p + 0x16); /* MapCollData.ceiling_count */
    port_swap16((u8*) p + 0x18); /* MapCollData.right_wall_start */
    port_swap16((u8*) p + 0x1A); /* MapCollData.right_wall_count */
    port_swap16((u8*) p + 0x1C); /* MapCollData.left_wall_start */
    port_swap16((u8*) p + 0x1E); /* MapCollData.left_wall_count */
    port_swap16((u8*) p + 0x20); /* MapCollData.dynamic_start */
    port_swap16((u8*) p + 0x22); /* MapCollData.dynamic_count */
    port_swap32((u8*) p + 0x28); /* MapCollData.joint_count */
    port_swap32((u8*) p + 0x2C); /* MapCollData.x2C */
}

/* MapLine: 0x10 bytes */
void port_swap_MapLine(void* p)
{
    port_swap16((u8*) p + 0x0); /* MapLine.v0_idx */
    port_swap16((u8*) p + 0x2); /* MapLine.v1_idx */
    port_swap16((u8*) p + 0x4); /* MapLine.prev_id0 */
    port_swap16((u8*) p + 0x6); /* MapLine.next_id0 */
    port_swap16((u8*) p + 0x8); /* MapLine.prev_id1 */
    port_swap16((u8*) p + 0xA); /* MapLine.next_id1 */
    port_swap16((u8*) p + 0xC); /* MapLine.hi_flags */
    port_swap16((u8*) p + 0xE); /* MapLine.lo_flags */
}

/* MapJoint: 0x28 bytes */
void port_swap_MapJoint(void* p)
{
    port_swap16((u8*) p + 0x0); /* MapJoint.floor_start */
    port_swap16((u8*) p + 0x2); /* MapJoint.floor_count */
    port_swap16((u8*) p + 0x4); /* MapJoint.ceiling_start */
    port_swap16((u8*) p + 0x6); /* MapJoint.ceiling_count */
    port_swap16((u8*) p + 0x8); /* MapJoint.right_wall_start */
    port_swap16((u8*) p + 0xA); /* MapJoint.right_wall_count */
    port_swap16((u8*) p + 0xC); /* MapJoint.left_wall_start */
    port_swap16((u8*) p + 0xE); /* MapJoint.left_wall_count */
    port_swap16((u8*) p + 0x10); /* MapJoint.dynamic_start */
    port_swap16((u8*) p + 0x12); /* MapJoint.dynamic_count */
    port_swap32((u8*) p + 0x14); /* MapJoint.left_bound */
    port_swap32((u8*) p + 0x18); /* MapJoint.bottom_bound */
    port_swap32((u8*) p + 0x1C); /* MapJoint.right_bound */
    port_swap32((u8*) p + 0x20); /* MapJoint.top_bound */
    port_swap16((u8*) p + 0x24); /* MapJoint.vtx_start */
    port_swap16((u8*) p + 0x26); /* MapJoint.vtx_count */
}

/* UnkStageDat: 0x30 bytes */
void port_swap_UnkStageDat(void* p)
{
    port_swap32((u8*) p + 0x4); /* UnkStageDat.unk4 */
    port_swap32((u8*) p + 0xC); /* UnkStageDat.unkC */
    port_swap32((u8*) p + 0x14); /* UnkStageDat.unk14 */
    port_swap32((u8*) p + 0x1C); /* UnkStageDat.unk1C */
    port_swap32((u8*) p + 0x24); /* UnkStageDat.unk24 */
    port_swap32((u8*) p + 0x2C); /* UnkStageDat.unk2C */
}

/* UnkStageDat_x8_t: 0x34 bytes */
void port_swap_UnkStageDat_x8_t(void* p)
{
    port_swap32((u8*) p + 0x24); /* UnkStageDat_x8_t.unk24 */
    port_swap32((u8*) p + 0x30); /* UnkStageDat_x8_t.x30 */
}

/* GroundShadowEntry: 0x8 bytes */
void port_swap_GroundShadowEntry(void* p)
{
    if (port_claim((u8*) p + 0x4, 1)) { /* bitfields: GroundShadowEntry.flag */
        u8* b = (u8*) p + 0x4;
        u32 be = ((u32) b[0] << 0);
        u32 host = 0;
        host |= ((be >> 7) & 0x1u) << 0;
        *(u8*) b = (u8) host;
    }
}

/* GrJoint: 0x6 bytes */
void port_swap_GrJoint(void* p)
{
    port_swap16((u8*) p + 0x0); /* GrJoint.x */
    port_swap16((u8*) p + 0x2); /* GrJoint.y */
    port_swap16((u8*) p + 0x4); /* GrJoint.z */
}

/* ftCo_DatAttrs: 0x184 bytes */
void port_swap_ftCo_DatAttrs(void* p)
{
    port_swap32((u8*) p + 0x0); /* ftCo_DatAttrs.walk_accel_mul */
    port_swap32((u8*) p + 0x4); /* ftCo_DatAttrs.walk_accel_base */
    port_swap32((u8*) p + 0x8); /* ftCo_DatAttrs.walk_max_vel */
    port_swap32((u8*) p + 0xC); /* ftCo_DatAttrs.slow_walk_max */
    port_swap32((u8*) p + 0x10); /* ftCo_DatAttrs.mid_walk_point */
    port_swap32((u8*) p + 0x14); /* ftCo_DatAttrs.fast_walk_min */
    port_swap32((u8*) p + 0x18); /* ftCo_DatAttrs.ground_friction */
    port_swap32((u8*) p + 0x1C); /* ftCo_DatAttrs.dash_initial_velocity */
    port_swap32((u8*) p + 0x20); /* ftCo_DatAttrs.dash_accel_mul */
    port_swap32((u8*) p + 0x24); /* ftCo_DatAttrs.dash_accel_base */
    port_swap32((u8*) p + 0x28); /* ftCo_DatAttrs.dash_max_velocity */
    port_swap32((u8*) p + 0x2C); /* ftCo_DatAttrs.run_animation_scaling */
    port_swap32((u8*) p + 0x30); /* ftCo_DatAttrs.max_run_brake_frames */
    port_swap32((u8*) p + 0x34); /* ftCo_DatAttrs.ground_max_horizontal_velocity */
    port_swap32((u8*) p + 0x38); /* ftCo_DatAttrs.jump_startup_time */
    port_swap32((u8*) p + 0x3C); /* ftCo_DatAttrs.jump_h_initial_velocity */
    port_swap32((u8*) p + 0x40); /* ftCo_DatAttrs.jump_v_initial_velocity */
    port_swap32((u8*) p + 0x44); /* ftCo_DatAttrs.ground_to_air_jump_momentum_multiplier */
    port_swap32((u8*) p + 0x48); /* ftCo_DatAttrs.jump_h_max_velocity */
    port_swap32((u8*) p + 0x4C); /* ftCo_DatAttrs.hop_v_initial_velocity */
    port_swap32((u8*) p + 0x50); /* ftCo_DatAttrs.air_jump_v_multiplier */
    port_swap32((u8*) p + 0x54); /* ftCo_DatAttrs.air_jump_h_multiplier */
    port_swap32((u8*) p + 0x58); /* ftCo_DatAttrs.max_jumps */
    port_swap32((u8*) p + 0x5C); /* ftCo_DatAttrs.gravity */
    port_swap32((u8*) p + 0x60); /* ftCo_DatAttrs.terminal_velocity */
    port_swap32((u8*) p + 0x64); /* ftCo_DatAttrs.air_drift_stick_mul */
    port_swap32((u8*) p + 0x68); /* ftCo_DatAttrs.aerial_drift_base */
    port_swap32((u8*) p + 0x6C); /* ftCo_DatAttrs.air_drift_max */
    port_swap32((u8*) p + 0x70); /* ftCo_DatAttrs.aerial_friction */
    port_swap32((u8*) p + 0x74); /* ftCo_DatAttrs.fast_fall_velocity */
    port_swap32((u8*) p + 0x78); /* ftCo_DatAttrs.air_max_horizontal_velocity */
    port_swap32((u8*) p + 0x7C); /* ftCo_DatAttrs.jab_2_input_window */
    port_swap32((u8*) p + 0x80); /* ftCo_DatAttrs.jab_3_input_window */
    port_swap32((u8*) p + 0x84); /* ftCo_DatAttrs.standing_turn_frames */
    port_swap32((u8*) p + 0x88); /* ftCo_DatAttrs.weight */
    port_swap32((u8*) p + 0x8C); /* ftCo_DatAttrs.model_scaling */
    port_swap32((u8*) p + 0x90); /* ftCo_DatAttrs.initial_shield_size */
    port_swap32((u8*) p + 0x94); /* ftCo_DatAttrs.shield_break_initial_velocity */
    port_swap32((u8*) p + 0x98); /* ftCo_DatAttrs.rapid_jab_window */
    port_swap32((u8*) p + 0x9C); /* ftCo_DatAttrs.clank_animation_length */
    port_swap32((u8*) p + 0xA0); /* ftCo_DatAttrs.hit_spark_variant */
    port_swap32((u8*) p + 0xA4); /* ftCo_DatAttrs.unused_0 */
    port_swap32((u8*) p + 0xA8); /* ftCo_DatAttrs.ledge_jump_horizontal_velocity */
    port_swap32((u8*) p + 0xAC); /* ftCo_DatAttrs.ledge_jump_vertical_velocity */
    port_swap32((u8*) p + 0xB0); /* ftCo_DatAttrs.item_throw_velocity_multiplier */
    port_swap32((u8*) p + 0xB4); /* ftCo_DatAttrs.heavy_throw_velocity_multiplier */
    port_swap32((u8*) p + 0xB8); /* ftCo_DatAttrs.specials_ground_speed_retention */
    port_swap32((u8*) p + 0xBC); /* ftCo_DatAttrs.xBC.size */
    port_swap32((u8*) p + 0xC0); /* ftCo_DatAttrs.xBC.x4.x */
    port_swap32((u8*) p + 0xC4); /* ftCo_DatAttrs.xBC.x4.y */
    port_swap32((u8*) p + 0xC8); /* ftCo_DatAttrs.xBC.x4.z */
    port_swap32((u8*) p + 0xCC); /* ftCo_DatAttrs.xBC.x10.x */
    port_swap32((u8*) p + 0xD0); /* ftCo_DatAttrs.xBC.x10.y */
    port_swap32((u8*) p + 0xD4); /* ftCo_DatAttrs.xBC.x10.z */
    port_swap32((u8*) p + 0xD8); /* ftCo_DatAttrs.xBC.x1C */
    port_swap32((u8*) p + 0xDC); /* ftCo_DatAttrs.xDC */
    port_swap32((u8*) p + 0xE0); /* ftCo_DatAttrs.kirby_b_star_damage */
    port_swap32((u8*) p + 0xE4); /* ftCo_DatAttrs.normal_landing_lag */
    port_swap32((u8*) p + 0xE8); /* ftCo_DatAttrs.landingairn_lag */
    port_swap32((u8*) p + 0xEC); /* ftCo_DatAttrs.landingairf_lag */
    port_swap32((u8*) p + 0xF0); /* ftCo_DatAttrs.landingairb_lag */
    port_swap32((u8*) p + 0xF4); /* ftCo_DatAttrs.landingairhi_lag */
    port_swap32((u8*) p + 0xF8); /* ftCo_DatAttrs.landingairlw_lag */
    port_swap32((u8*) p + 0xFC); /* ftCo_DatAttrs.name_tag_height */
    port_swap32((u8*) p + 0x100); /* ftCo_DatAttrs.passivewall_vel_x */
    port_swap32((u8*) p + 0x104); /* ftCo_DatAttrs.wall_jump_horizontal_velocity */
    port_swap32((u8*) p + 0x108); /* ftCo_DatAttrs.wall_jump_vertical_velocity */
    port_swap32((u8*) p + 0x10C); /* ftCo_DatAttrs.passiveceil_vel_x */
    port_swap32((u8*) p + 0x110); /* ftCo_DatAttrs.trophy_scale */
    port_swap32((u8*) p + 0x114); /* ftCo_DatAttrs.x114.x */
    port_swap32((u8*) p + 0x118); /* ftCo_DatAttrs.x114.y */
    port_swap32((u8*) p + 0x11C); /* ftCo_DatAttrs.x114.z */
    port_swap32((u8*) p + 0x120); /* ftCo_DatAttrs.x120.x */
    port_swap32((u8*) p + 0x124); /* ftCo_DatAttrs.x120.y */
    port_swap32((u8*) p + 0x128); /* ftCo_DatAttrs.x120.z */
    port_swap32((u8*) p + 0x12C); /* ftCo_DatAttrs.x12C */
    port_swap32((u8*) p + 0x130); /* ftCo_DatAttrs.x130.x */
    port_swap32((u8*) p + 0x134); /* ftCo_DatAttrs.x130.y */
    port_swap32((u8*) p + 0x138); /* ftCo_DatAttrs.x130.z */
    port_swap32((u8*) p + 0x13C); /* ftCo_DatAttrs.x13C */
    port_swap32((u8*) p + 0x140); /* ftCo_DatAttrs.screw_attack_launch_velocity */
    port_swap32((u8*) p + 0x144); /* ftCo_DatAttrs.x144 */
    port_swap32((u8*) p + 0x148); /* ftCo_DatAttrs.wall_jump_min_approach_speed */
    port_swap32((u8*) p + 0x14C); /* ftCo_DatAttrs.damageice_ice_size */
    port_swap32((u8*) p + 0x150); /* ftCo_DatAttrs.x150_damageice_unk */
    port_swap32((u8*) p + 0x154); /* ftCo_DatAttrs.x154_damageice_unk */
    port_swap32((u8*) p + 0x158); /* ftCo_DatAttrs.damageicejump_vel_y */
    port_swap32((u8*) p + 0x15C); /* ftCo_DatAttrs.damageicejump_vel_x_mult */
    port_swap32((u8*) p + 0x160); /* ftCo_DatAttrs.respawn_platform_scale */
    port_swap32((u8*) p + 0x164); /* ftCo_DatAttrs.warp_star_hitbox_scale */
    port_swap32((u8*) p + 0x168); /* ftCo_DatAttrs.x168 */
    port_swap32((u8*) p + 0x16C); /* ftCo_DatAttrs.camera_zoom_target_bone */
    port_swap32((u8*) p + 0x170); /* ftCo_DatAttrs.x170.x */
    port_swap32((u8*) p + 0x174); /* ftCo_DatAttrs.x170.y */
    port_swap32((u8*) p + 0x178); /* ftCo_DatAttrs.x170.z */
    port_swap32((u8*) p + 0x17C); /* ftCo_DatAttrs.x17C */
}

/* ftCommonData: 0x818 bytes */
void port_swap_ftCommonData(void* p)
{
    port_swap32((u8*) p + 0x0); /* ftCommonData.horizontal_stick_deadzone */
    port_swap32((u8*) p + 0x4); /* ftCommonData.vertical_stick_deadzone */
    port_swap32((u8*) p + 0x8); /* ftCommonData.horizontal_stick_smash_deadzone */
    port_swap32((u8*) p + 0xC); /* ftCommonData.vertical_stick_smash_deadzone */
    port_swap32((u8*) p + 0x10); /* ftCommonData.analog_shoulder_deadzone */
    port_swap32((u8*) p + 0x14); /* ftCommonData.z_press_analog_value */
    port_swap32((u8*) p + 0x18); /* ftCommonData.shield_press_threshold */
    port_swap32((u8*) p + 0x1C); /* ftCommonData.x1C */
    port_swap32((u8*) p + 0x20); /* ftCommonData.x20_radians */
    port_swap32((u8*) p + 0x24); /* ftCommonData.walk_stick_threshold */
    port_swap32((u8*) p + 0x28); /* ftCommonData.walk_middle_animation_stick_threshold */
    port_swap32((u8*) p + 0x2C); /* ftCommonData.walk_fast_stick_threshold */
    port_swap32((u8*) p + 0x30); /* ftCommonData.walk_accel_taper_gain */
    port_swap32((u8*) p + 0x34); /* ftCommonData.x34 */
    port_swap32((u8*) p + 0x38); /* ftCommonData.x38_someLStickXThreshold */
    port_swap32((u8*) p + 0x3C); /* ftCommonData.dash_smash_stick_threshold */
    port_swap32((u8*) p + 0x40); /* ftCommonData.dash_smash_window */
    port_swap32((u8*) p + 0x44); /* ftCommonData.x44 */
    port_swap32((u8*) p + 0x48); /* ftCommonData.x48 */
    port_swap32((u8*) p + 0x4C); /* ftCommonData.x4C */
    port_swap32((u8*) p + 0x50); /* ftCommonData.x50 */
    port_swap32((u8*) p + 0x54); /* ftCommonData.x54 */
    port_swap32((u8*) p + 0x58); /* ftCommonData.x58_someLStickXThreshold */
    port_swap32((u8*) p + 0x5C); /* ftCommonData.run_accel_taper_gain */
    port_swap32((u8*) p + 0x60); /* ftCommonData.run_dash_turn_friction_multiplier */
    port_swap32((u8*) p + 0x64); /* ftCommonData.x64 */
    port_swap32((u8*) p + 0x68); /* ftCommonData.x68 */
    port_swap32((u8*) p + 0x6C); /* ftCommonData.friction_when_above_walk_speed */
    port_swap32((u8*) p + 0x70); /* ftCommonData.tap_jump_threshold */
    port_swap32((u8*) p + 0x74); /* ftCommonData.tap_jump_window */
    port_swap32((u8*) p + 0x78); /* ftCommonData.x78 */
    port_swap32((u8*) p + 0x7C); /* ftCommonData.tap_jump_release_threshold */
    port_swap32((u8*) p + 0x80); /* ftCommonData.relaxed_tap_jump_threshold */
    port_swap32((u8*) p + 0x84); /* ftCommonData.x84 */
    port_swap32((u8*) p + 0x88); /* ftCommonData.x88 */
    port_swap32((u8*) p + 0x8C); /* ftCommonData.x8C */
    port_swap32((u8*) p + 0x90); /* ftCommonData.x90 */
    port_swap32((u8*) p + 0x94); /* ftCommonData.x94 */
    port_swap32((u8*) p + 0x98); /* ftCommonData.x98 */
    port_swap32((u8*) p + 0x9C); /* ftCommonData.x9C_radians */
    port_swap32((u8*) p + 0xA0); /* ftCommonData.xA0_radians */
    port_swap32((u8*) p + 0xA4); /* ftCommonData.xA4_radians */
    port_swap32((u8*) p + 0xA8); /* ftCommonData.xA8_radians */
    port_swap32((u8*) p + 0xAC); /* ftCommonData.attackhi3_stick_threshold_y */
    port_swap32((u8*) p + 0xB0); /* ftCommonData.xB0 */
    port_swap32((u8*) p + 0xB4); /* ftCommonData.xB4 */
    port_swap32((u8*) p + 0xB8); /* ftCommonData.xB8_radians */
    port_swap32((u8*) p + 0xBC); /* ftCommonData.xBC_radians */
    port_swap32((u8*) p + 0xC0); /* ftCommonData.xC0_radians */
    port_swap32((u8*) p + 0xC4); /* ftCommonData.xC4_radians */
    port_swap32((u8*) p + 0xC8); /* ftCommonData.xC8 */
    port_swap32((u8*) p + 0xCC); /* ftCommonData.xCC */
    port_swap32((u8*) p + 0xD0); /* ftCommonData.xD0 */
    port_swap32((u8*) p + 0xD4); /* ftCommonData.xD4 */
    port_swap32((u8*) p + 0xD8); /* ftCommonData.xD8 */
    port_swap32((u8*) p + 0xDC); /* ftCommonData.xDC */
    port_swap32((u8*) p + 0xE0); /* ftCommonData.xE0 */
    port_swap32((u8*) p + 0xE4); /* ftCommonData.xE4 */
    port_swap32((u8*) p + 0xE8); /* ftCommonData.xE8 */
    port_swap32((u8*) p + 0xEC); /* ftCommonData.xEC */
    port_swap32((u8*) p + 0xF0); /* ftCommonData.xF0 */
    port_swap32((u8*) p + 0xF4); /* ftCommonData.xF4 */
    port_swap32((u8*) p + 0xF8); /* ftCommonData.xF8 */
    port_swap32((u8*) p + 0xFC); /* ftCommonData.xFC */
    port_swap32((u8*) p + 0x100); /* ftCommonData.x100 */
    port_swap32((u8*) p + 0x104); /* ftCommonData.kb_min */
    port_swap32((u8*) p + 0x108); /* ftCommonData.x108 */
    port_swap32((u8*) p + 0x10C); /* ftCommonData.x10C */
    port_swap32((u8*) p + 0x110); /* ftCommonData.x110 */
    port_swap32((u8*) p + 0x114); /* ftCommonData.x114 */
    port_swap32((u8*) p + 0x118); /* ftCommonData.x118 */
    port_swap32((u8*) p + 0x11C); /* ftCommonData.x11C */
    port_swap32((u8*) p + 0x120); /* ftCommonData.x120 */
    port_swap32((u8*) p + 0x124); /* ftCommonData.kb_squat_mul */
    port_swap32((u8*) p + 0x128); /* ftCommonData.x128 */
    port_swap32((u8*) p + 0x12C); /* ftCommonData.x12C */
    port_swap32((u8*) p + 0x130); /* ftCommonData.x130 */
    port_swap32((u8*) p + 0x134); /* ftCommonData.x134 */
    port_swap32((u8*) p + 0x138); /* ftCommonData.x138 */
    port_swap32((u8*) p + 0x13C); /* ftCommonData.x13C */
    port_swap32((u8*) p + 0x140); /* ftCommonData.x140 */
    port_swap32((u8*) p + 0x144); /* ftCommonData.x144_radians */
    port_swap32((u8*) p + 0x148); /* ftCommonData.x148 */
    port_swap32((u8*) p + 0x14C); /* ftCommonData.x14C */
    port_swap32((u8*) p + 0x150); /* ftCommonData.x150 */
    port_swap32((u8*) p + 0x154); /* ftCommonData.x154 */
    port_swap32((u8*) p + 0x158); /* ftCommonData.x158 */
    port_swap32((u8*) p + 0x15C); /* ftCommonData.x15C */
    port_swap32((u8*) p + 0x160); /* ftCommonData.x160 */
    port_swap32((u8*) p + 0x164); /* ftCommonData.max_grounded_kb_on_landing */
    port_swap32((u8*) p + 0x168); /* ftCommonData.x168 */
    port_swap32((u8*) p + 0x16C); /* ftCommonData.x16C */
    port_swap32((u8*) p + 0x170); /* ftCommonData.x170 */
    port_swap32((u8*) p + 0x174); /* ftCommonData.x174 */
    port_swap32((u8*) p + 0x178); /* ftCommonData.x178 */
    port_swap32((u8*) p + 0x17C); /* ftCommonData.x17C */
    port_swap32((u8*) p + 0x180); /* ftCommonData.x180 */
    port_swap32((u8*) p + 0x184); /* ftCommonData.x184 */
    port_swap32((u8*) p + 0x188); /* ftCommonData.x188 */
    port_swap32((u8*) p + 0x18C); /* ftCommonData.x18C */
    port_swap32((u8*) p + 0x190); /* ftCommonData.x190 */
    port_swap32((u8*) p + 0x194); /* ftCommonData.x194_unkHitLagFrames */
    port_swap32((u8*) p + 0x198); /* ftCommonData.x198 */
    port_swap32((u8*) p + 0x19C); /* ftCommonData.x19C */
    port_swap32((u8*) p + 0x1A0); /* ftCommonData.x1A0 */
    port_swap32((u8*) p + 0x1A4); /* ftCommonData.x1A4 */
    port_swap32((u8*) p + 0x1A8); /* ftCommonData.x1A8 */
    port_swap32((u8*) p + 0x1AC); /* ftCommonData.x1AC */
    port_swap32((u8*) p + 0x1B0); /* ftCommonData.x1B0 */
    port_swap32((u8*) p + 0x1B4); /* ftCommonData.x1B4 */
    port_swap32((u8*) p + 0x1B8); /* ftCommonData.x1B8 */
    port_swap32((u8*) p + 0x1BC); /* ftCommonData.x1BC */
    port_swap32((u8*) p + 0x1C0); /* ftCommonData.x1C0 */
    port_swap32((u8*) p + 0x1C4); /* ftCommonData.x1C4 */
    port_swap32((u8*) p + 0x1C8); /* ftCommonData.x1C8 */
    port_swap32((u8*) p + 0x1CC); /* ftCommonData.x1CC */
    port_swap32((u8*) p + 0x1D0); /* ftCommonData.x1D0 */
    port_swap32((u8*) p + 0x1D4); /* ftCommonData.x1D4 */
    port_swap32((u8*) p + 0x1D8); /* ftCommonData.x1D8 */
    port_swap32((u8*) p + 0x1DC); /* ftCommonData.x1DC */
    port_swap32((u8*) p + 0x1E0); /* ftCommonData.x1E0 */
    port_swap32((u8*) p + 0x1E4); /* ftCommonData.x1E4 */
    port_swap32((u8*) p + 0x1E8); /* ftCommonData.x1E8_radians */
    port_swap32((u8*) p + 0x1EC); /* ftCommonData.x1EC */
    port_swap32((u8*) p + 0x1F0); /* ftCommonData.x1F0 */
    port_swap32((u8*) p + 0x1F4); /* ftCommonData.x1F4 */
    port_swap32((u8*) p + 0x1F8); /* ftCommonData.x1F8 */
    port_swap32((u8*) p + 0x1FC); /* ftCommonData.aerial_friction_oob */
    port_swap32((u8*) p + 0x200); /* ftCommonData.x200 */
    port_swap32((u8*) p + 0x204); /* ftCommonData.x204_knockbackFrameDecay */
    port_swap32((u8*) p + 0x208); /* ftCommonData.x208 */
    port_swap32((u8*) p + 0x20C); /* ftCommonData.x20C */
    port_swap32((u8*) p + 0x210); /* ftCommonData.x210 */
    port_swap32((u8*) p + 0x214); /* ftCommonData.x214 */
    port_swap32((u8*) p + 0x218); /* ftCommonData.x218 */
    port_swap32((u8*) p + 0x21C); /* ftCommonData.x21C */
    port_swap32((u8*) p + 0x220); /* ftCommonData.x220 */
    port_swap32((u8*) p + 0x224); /* ftCommonData.x224 */
    port_swap32((u8*) p + 0x228); /* ftCommonData.x228 */
    port_swap32((u8*) p + 0x22C); /* ftCommonData.x22C */
    port_swap32((u8*) p + 0x230); /* ftCommonData.x230 */
    port_swap32((u8*) p + 0x234); /* ftCommonData.x234_radians */
    port_swap32((u8*) p + 0x238); /* ftCommonData.x238_radians */
    port_swap32((u8*) p + 0x23C); /* ftCommonData.x23C */
    port_swap32((u8*) p + 0x240); /* ftCommonData.x240 */
    port_swap32((u8*) p + 0x244); /* ftCommonData.x244 */
    port_swap32((u8*) p + 0x248); /* ftCommonData.x248 */
    port_swap32((u8*) p + 0x24C); /* ftCommonData.x24C */
    port_swap32((u8*) p + 0x250); /* ftCommonData.x250 */
    port_swap32((u8*) p + 0x254); /* ftCommonData.x254 */
    port_swap32((u8*) p + 0x258); /* ftCommonData.x258 */
    port_swap32((u8*) p + 0x25C); /* ftCommonData.x25C */
    port_swap32((u8*) p + 0x260); /* ftCommonData.x260_startShieldHealth */
    port_swap32((u8*) p + 0x264); /* ftCommonData.x264 */
    port_swap32((u8*) p + 0x268); /* ftCommonData.x268 */
    port_swap32((u8*) p + 0x26C); /* ftCommonData.x26C */
    port_swap32((u8*) p + 0x270); /* ftCommonData.x270 */
    port_swap32((u8*) p + 0x274); /* ftCommonData.x274 */
    port_swap32((u8*) p + 0x278); /* ftCommonData.x278 */
    port_swap32((u8*) p + 0x27C); /* ftCommonData.x27C */
    port_swap32((u8*) p + 0x280); /* ftCommonData.x280_unkShieldHealth */
    port_swap32((u8*) p + 0x284); /* ftCommonData.x284 */
    port_swap32((u8*) p + 0x288); /* ftCommonData.x288 */
    port_swap32((u8*) p + 0x28C); /* ftCommonData.x28C */
    port_swap32((u8*) p + 0x290); /* ftCommonData.x290 */
    port_swap32((u8*) p + 0x294); /* ftCommonData.x294 */
    port_swap32((u8*) p + 0x298); /* ftCommonData.x298 */
    port_swap32((u8*) p + 0x29C); /* ftCommonData.x29C */
    port_swap32((u8*) p + 0x2A0); /* ftCommonData.powershield_input_window */
    port_swap32((u8*) p + 0x2A4); /* ftCommonData.x2A4 */
    port_swap32((u8*) p + 0x2A8); /* ftCommonData.x2A8 */
    port_swap32((u8*) p + 0x2AC); /* ftCommonData.x2AC */
    port_swap32((u8*) p + 0x2B0); /* ftCommonData.x2B0 */
    port_swap32((u8*) p + 0x2B4); /* ftCommonData.x2B4 */
    port_swap32((u8*) p + 0x2B8); /* ftCommonData.x2B8 */
    port_swap32((u8*) p + 0x2BC); /* ftCommonData.x2BC */
    port_swap32((u8*) p + 0x2C0); /* ftCommonData.x2C0 */
    port_swap32((u8*) p + 0x2C4); /* ftCommonData.x2C4 */
    port_swap32((u8*) p + 0x2C8); /* ftCommonData.x2C8 */
    port_swap32((u8*) p + 0x2CC); /* ftCommonData.x2CC */
    port_swap32((u8*) p + 0x2D0); /* ftCommonData.x2D0 */
    port_swap32((u8*) p + 0x2D4); /* ftCommonData.x2D4 */
    port_swap32((u8*) p + 0x2D8); /* ftCommonData.x2D8 */
    port_swap32((u8*) p + 0x2DC); /* ftCommonData.x2DC */
    port_swap32((u8*) p + 0x2E0); /* ftCommonData.x2E0 */
    port_swap32((u8*) p + 0x2E4); /* ftCommonData.x2E4 */
    port_swap32((u8*) p + 0x2E8); /* ftCommonData.x2E8 */
    port_swap32((u8*) p + 0x2EC); /* ftCommonData.x2EC */
    port_swap32((u8*) p + 0x2F0); /* ftCommonData.x2F0 */
    port_swap32((u8*) p + 0x2F4); /* ftCommonData.x2F4 */
    port_swap32((u8*) p + 0x2F8); /* ftCommonData.x2F8 */
    port_swap32((u8*) p + 0x2FC); /* ftCommonData.x2FC */
    port_swap32((u8*) p + 0x300); /* ftCommonData.x300 */
    port_swap32((u8*) p + 0x304); /* ftCommonData.x304 */
    port_swap32((u8*) p + 0x308); /* ftCommonData.x308 */
    port_swap32((u8*) p + 0x30C); /* ftCommonData.x30C */
    port_swap32((u8*) p + 0x310); /* ftCommonData.x310 */
    port_swap32((u8*) p + 0x314); /* ftCommonData.x314 */
    port_swap32((u8*) p + 0x318); /* ftCommonData.x318 */
    port_swap32((u8*) p + 0x31C); /* ftCommonData.x31C */
    port_swap32((u8*) p + 0x320); /* ftCommonData.x320 */
    port_swap32((u8*) p + 0x324); /* ftCommonData.x324 */
    port_swap32((u8*) p + 0x328); /* ftCommonData.x328 */
    port_swap32((u8*) p + 0x32C); /* ftCommonData.escapeair_deadzone.x */
    port_swap32((u8*) p + 0x330); /* ftCommonData.escapeair_deadzone.y */
    port_swap32((u8*) p + 0x334); /* ftCommonData.x334 */
    port_swap32((u8*) p + 0x338); /* ftCommonData.escapeair_force */
    port_swap32((u8*) p + 0x33C); /* ftCommonData.escapeair_decay */
    port_swap32((u8*) p + 0x340); /* ftCommonData.x340 */
    port_swap32((u8*) p + 0x344); /* ftCommonData.x344 */
    port_swap32((u8*) p + 0x348); /* ftCommonData.x348 */
    port_swap32((u8*) p + 0x34C); /* ftCommonData.x34C */
    port_swap32((u8*) p + 0x350); /* ftCommonData.x350 */
    port_swap32((u8*) p + 0x354); /* ftCommonData.x354 */
    port_swap32((u8*) p + 0x358); /* ftCommonData.x358 */
    port_swap32((u8*) p + 0x35C); /* ftCommonData.x35C */
    port_swap32((u8*) p + 0x360); /* ftCommonData.x360 */
    port_swap32((u8*) p + 0x364); /* ftCommonData.x364 */
    port_swap32((u8*) p + 0x368); /* ftCommonData.x368 */
    port_swap32((u8*) p + 0x36C); /* ftCommonData.x36C */
    port_swap32((u8*) p + 0x370); /* ftCommonData.x370 */
    port_swap32((u8*) p + 0x374); /* ftCommonData.x374 */
    port_swap32((u8*) p + 0x378); /* ftCommonData.x378 */
    port_swap32((u8*) p + 0x37C); /* ftCommonData.x37C */
    port_swap32((u8*) p + 0x380); /* ftCommonData.x380.state */
    port_swap32((u8*) p + 0x384); /* ftCommonData.x380.damage */
    port_swap32((u8*) p + 0x388); /* ftCommonData.x380.kb_angle */
    port_swap32((u8*) p + 0x38C); /* ftCommonData.x380.unkC */
    port_swap32((u8*) p + 0x390); /* ftCommonData.x380.unk10 */
    port_swap32((u8*) p + 0x394); /* ftCommonData.x380.unk14 */
    port_swap32((u8*) p + 0x398); /* ftCommonData.x380.element */
    port_swap32((u8*) p + 0x39C); /* ftCommonData.x380.sfx_severity */
    port_swap32((u8*) p + 0x3A0); /* ftCommonData.x380.sfx_kind */
    port_swap32((u8*) p + 0x3A4); /* ftCommonData.grab_timer_decrement */
    port_swap32((u8*) p + 0x3A8); /* ftCommonData.x3A8 */
    port_swap32((u8*) p + 0x3AC); /* ftCommonData.x3AC */
    port_swap32((u8*) p + 0x3B0); /* ftCommonData.x3B0 */
    port_swap32((u8*) p + 0x3B4); /* ftCommonData.shouldered_anim_rate */
    port_swap32((u8*) p + 0x3B8); /* ftCommonData.x3B8 */
    port_swap32((u8*) p + 0x3BC); /* ftCommonData.x3BC */
    port_swap32((u8*) p + 0x3C0); /* ftCommonData.x3C0 */
    port_swap32((u8*) p + 0x3C4); /* ftCommonData.x3C4 */
    port_swap32((u8*) p + 0x3C8); /* ftCommonData.x3C8 */
    port_swap32((u8*) p + 0x3CC); /* ftCommonData.x3CC */
    port_swap32((u8*) p + 0x3D0); /* ftCommonData.x3D0 */
    port_swap32((u8*) p + 0x3D4); /* ftCommonData.x3D4 */
    port_swap32((u8*) p + 0x3D8); /* ftCommonData.x3D8 */
    port_swap32((u8*) p + 0x3DC); /* ftCommonData.x3DC */
    port_swap32((u8*) p + 0x3E0); /* ftCommonData.x3E0 */
    port_swap32((u8*) p + 0x3E4); /* ftCommonData.x3E4 */
    port_swap32((u8*) p + 0x3E8); /* ftCommonData.x3E8_shieldKnockbackFrameDecay */
    port_swap32((u8*) p + 0x3EC); /* ftCommonData.x3EC_shieldGroundFrictionMultiplier */
    port_swap32((u8*) p + 0x3F0); /* ftCommonData.x3F0 */
    port_swap32((u8*) p + 0x3F4); /* ftCommonData.x3F4 */
    port_swap32((u8*) p + 0x3F8); /* ftCommonData.x3F8 */
    port_swap32((u8*) p + 0x3FC); /* ftCommonData.x3FC */
    port_swap32((u8*) p + 0x400); /* ftCommonData.x400 */
    port_swap32((u8*) p + 0x404); /* ftCommonData.x404 */
    port_swap32((u8*) p + 0x408); /* ftCommonData.x408 */
    port_swap32((u8*) p + 0x40C); /* ftCommonData.x40C */
    port_swap32((u8*) p + 0x410); /* ftCommonData.x410 */
    port_swap32((u8*) p + 0x414); /* ftCommonData.x414 */
    port_swap32((u8*) p + 0x418); /* ftCommonData.x418 */
    port_swap32((u8*) p + 0x41C); /* ftCommonData.x41C */
    port_swap32((u8*) p + 0x420); /* ftCommonData.x420 */
    port_swap32((u8*) p + 0x424); /* ftCommonData.x424 */
    port_swap32((u8*) p + 0x428); /* ftCommonData.x428 */
    port_swap32((u8*) p + 0x42C); /* ftCommonData.x42C */
    port_swap32((u8*) p + 0x430); /* ftCommonData.x430 */
    port_swap32((u8*) p + 0x434); /* ftCommonData.x434 */
    port_swap32((u8*) p + 0x438); /* ftCommonData.x438 */
    port_swap32((u8*) p + 0x43C); /* ftCommonData.x43C */
    port_swap32((u8*) p + 0x440); /* ftCommonData.x440 */
    port_swap32((u8*) p + 0x444); /* ftCommonData.x444 */
    port_swap32((u8*) p + 0x448); /* ftCommonData.x448 */
    port_swap32((u8*) p + 0x44C); /* ftCommonData.x44C */
    port_swap32((u8*) p + 0x450); /* ftCommonData.x450 */
    port_swap32((u8*) p + 0x454); /* ftCommonData.x454 */
    port_swap32((u8*) p + 0x458); /* ftCommonData.x458 */
    port_swap32((u8*) p + 0x45C); /* ftCommonData.x45C */
    port_swap32((u8*) p + 0x460); /* ftCommonData.x460 */
    port_swap32((u8*) p + 0x464); /* ftCommonData.x464 */
    port_swap32((u8*) p + 0x468); /* ftCommonData.x468 */
    port_swap32((u8*) p + 0x46C); /* ftCommonData.x46C */
    port_swap32((u8*) p + 0x470); /* ftCommonData.x470 */
    port_swap32((u8*) p + 0x474); /* ftCommonData.teeter_walk_threshold */
    port_swap32((u8*) p + 0x478); /* ftCommonData.x478 */
    port_swap32((u8*) p + 0x47C); /* ftCommonData.x47C */
    port_swap32((u8*) p + 0x480); /* ftCommonData.x480 */
    port_swap32((u8*) p + 0x484); /* ftCommonData.x484 */
    port_swap32((u8*) p + 0x488); /* ftCommonData.x488 */
    port_swap32((u8*) p + 0x48C); /* ftCommonData.x48C */
    port_swap32((u8*) p + 0x490); /* ftCommonData.x490 */
    port_swap32((u8*) p + 0x494); /* ftCommonData.x494 */
    port_swap32((u8*) p + 0x498); /* ftCommonData.ledge_cooldown */
    port_swap32((u8*) p + 0x49C); /* ftCommonData.x49C */
    port_swap32((u8*) p + 0x4A0); /* ftCommonData.x4A0 */
    port_swap32((u8*) p + 0x4A4); /* ftCommonData.x4A4 */
    port_swap32((u8*) p + 0x4A8); /* ftCommonData.x4A8 */
    port_swap32((u8*) p + 0x4AC); /* ftCommonData.x4AC */
    port_swap32((u8*) p + 0x4B0); /* ftCommonData.sdi_min_stick_mag */
    port_swap32((u8*) p + 0x4B4); /* ftCommonData.sdi_stick_window */
    port_swap32((u8*) p + 0x4B8); /* ftCommonData.sdi_pos_scale */
    port_swap32((u8*) p + 0x4BC); /* ftCommonData.x4BC */
    port_swap32((u8*) p + 0x4C0); /* ftCommonData.x4C0 */
    port_swap32((u8*) p + 0x4C4); /* ftCommonData.x4C4 */
    port_swap32((u8*) p + 0x4C8); /* ftCommonData.x4C8 */
    port_swap32((u8*) p + 0x4CC); /* ftCommonData.x4CC */
    port_swap32((u8*) p + 0x4D0); /* ftCommonData.x4D0 */
    port_swap32((u8*) p + 0x4D4); /* ftCommonData.x4D4 */
    port_swap32((u8*) p + 0x4D8); /* ftCommonData.x4D8 */
    port_swap32((u8*) p + 0x4DC); /* ftCommonData.x4DC.x */
    port_swap32((u8*) p + 0x4E0); /* ftCommonData.x4DC.y */
    port_swap32((u8*) p + 0x4E4); /* ftCommonData.x4E4.x */
    port_swap32((u8*) p + 0x4E8); /* ftCommonData.x4E4.y */
    port_swap32((u8*) p + 0x4EC); /* ftCommonData.x4E4.z */
    port_swap32((u8*) p + 0x4F0); /* ftCommonData.x4F0 */
    port_swap32((u8*) p + 0x4F4); /* ftCommonData.x4F4 */
    port_swap32((u8*) p + 0x4F8); /* ftCommonData.x4F8 */
    port_swap32((u8*) p + 0x4FC); /* ftCommonData.x4FC */
    port_swap32((u8*) p + 0x500); /* ftCommonData.x500 */
    port_swap32((u8*) p + 0x504); /* ftCommonData.x504 */
    port_swap32((u8*) p + 0x508); /* ftCommonData.x508 */
    port_swap32((u8*) p + 0x50C); /* ftCommonData.x50C */
    port_swap32((u8*) p + 0x510); /* ftCommonData.x510 */
    port_swap32((u8*) p + 0x514); /* ftCommonData.x514 */
    port_swap32((u8*) p + 0x518); /* ftCommonData.x518 */
    port_swap32((u8*) p + 0x51C); /* ftCommonData.x51C_radians */
    port_swap32((u8*) p + 0x520); /* ftCommonData.fall_common.x520 */
    port_swap32((u8*) p + 0x524); /* ftCommonData.fall_common.x524 */
    port_swap32((u8*) p + 0x528); /* ftCommonData.fall_common.x528 */
    port_swap32((u8*) p + 0x52C); /* ftCommonData.fall_common.x52C */
    port_swap32((u8*) p + 0x530); /* ftCommonData.fall_common.x530 */
    port_swap32((u8*) p + 0x534); /* ftCommonData.fall_common.x534 */
    port_swap32((u8*) p + 0x538); /* ftCommonData.fall_common.x538.x */
    port_swap32((u8*) p + 0x53C); /* ftCommonData.fall_common.x538.y */
    port_swap32((u8*) p + 0x540); /* ftCommonData.fall_common.x538.z */
    port_swap32((u8*) p + 0x544); /* ftCommonData.fall_common.x544.x */
    port_swap32((u8*) p + 0x548); /* ftCommonData.fall_common.x544.y */
    port_swap32((u8*) p + 0x54C); /* ftCommonData.fall_common.x544.z */
    port_swap32((u8*) p + 0x550); /* ftCommonData.fall_common.x550 */
    port_swap32((u8*) p + 0x554); /* ftCommonData.fall_common.x554 */
    port_swap32((u8*) p + 0x558); /* ftCommonData.fall_common.x558 */
    port_swap32((u8*) p + 0x55C); /* ftCommonData.fall_common.x55C */
    port_swap32((u8*) p + 0x560); /* ftCommonData.fall_common.x560_radians */
    port_swap32((u8*) p + 0x564); /* ftCommonData.fall_common.x564 */
    port_swap32((u8*) p + 0x568); /* ftCommonData.x568 */
    port_swap32((u8*) p + 0x56C); /* ftCommonData.x56C */
    port_swap32((u8*) p + 0x570); /* ftCommonData.x570 */
    port_swap32((u8*) p + 0x574); /* ftCommonData.x574 */
    port_swap32((u8*) p + 0x578); /* ftCommonData.x578 */
    port_swap32((u8*) p + 0x57C); /* ftCommonData.x57C */
    port_swap32((u8*) p + 0x580); /* ftCommonData.x580 */
    port_swap32((u8*) p + 0x584); /* ftCommonData.x584 */
    port_swap32((u8*) p + 0x588); /* ftCommonData.x588 */
    port_swap32((u8*) p + 0x58C); /* ftCommonData.x58C */
    port_swap32((u8*) p + 0x590); /* ftCommonData.x590 */
    port_swap32((u8*) p + 0x594); /* ftCommonData.open_parasol_threshold */
    port_swap32((u8*) p + 0x598); /* ftCommonData.close_parasol_threshold */
    port_swap32((u8*) p + 0x59C); /* ftCommonData.x59C */
    port_swap32((u8*) p + 0x5A0); /* ftCommonData.x5A0 */
    port_swap32((u8*) p + 0x5A4); /* ftCommonData.x5A4 */
    port_swap32((u8*) p + 0x5A8); /* ftCommonData.x5A8 */
    port_swap32((u8*) p + 0x5AC); /* ftCommonData.x5AC */
    port_swap32((u8*) p + 0x5B0); /* ftCommonData.x5B0 */
    port_swap32((u8*) p + 0x5B4); /* ftCommonData.x5B4 */
    port_swap32((u8*) p + 0x5B8); /* ftCommonData.x5B8 */
    port_swap32((u8*) p + 0x5BC); /* ftCommonData.x5BC */
    port_swap32((u8*) p + 0x5C0); /* ftCommonData.x5C0 */
    port_swap32((u8*) p + 0x5C4); /* ftCommonData.x5C4 */
    port_swap32((u8*) p + 0x5C8); /* ftCommonData.x5C8 */
    port_swap32((u8*) p + 0x5CC); /* ftCommonData.x5CC */
    port_swap32((u8*) p + 0x5D0); /* ftCommonData.rebirth_countdown */
    port_swap32((u8*) p + 0x5D4); /* ftCommonData.rebirth_wait */
    port_swap32((u8*) p + 0x5D8); /* ftCommonData.x5D8 */
    port_swap32((u8*) p + 0x5DC); /* ftCommonData.bury_timer_unk1 */
    port_swap32((u8*) p + 0x5E0); /* ftCommonData.bury_timer_unk2 */
    port_swap32((u8*) p + 0x5E4); /* ftCommonData.bury_timer_unk3 */
    port_swap32((u8*) p + 0x5E8); /* ftCommonData.x5E8 */
    port_swap32((u8*) p + 0x5EC); /* ftCommonData.x5EC */
    port_swap32((u8*) p + 0x5F0); /* ftCommonData.x5F0 */
    port_swap32((u8*) p + 0x5F4); /* ftCommonData.x5F4 */
    port_swap32((u8*) p + 0x5F8); /* ftCommonData.x5F8 */
    port_swap32((u8*) p + 0x5FC); /* ftCommonData.x5FC */
    port_swap32((u8*) p + 0x600); /* ftCommonData.x600 */
    port_swap32((u8*) p + 0x604); /* ftCommonData.x604 */
    port_swap32((u8*) p + 0x608); /* ftCommonData.x608 */
    port_swap32((u8*) p + 0x60C); /* ftCommonData.x60C */
    port_swap32((u8*) p + 0x610); /* ftCommonData.x610 */
    port_swap32((u8*) p + 0x614); /* ftCommonData.x614 */
    port_swap32((u8*) p + 0x618); /* ftCommonData.x618 */
    port_swap32((u8*) p + 0x61C); /* ftCommonData.x61C */
    port_swap32((u8*) p + 0x620); /* ftCommonData.x620 */
    port_swap32((u8*) p + 0x624); /* ftCommonData.x624 */
    port_swap32((u8*) p + 0x628); /* ftCommonData.x628 */
    port_swap32((u8*) p + 0x62C); /* ftCommonData.x62C */
    port_swap32((u8*) p + 0x630); /* ftCommonData.x630 */
    port_swap32((u8*) p + 0x634); /* ftCommonData.x634 */
    port_swap32((u8*) p + 0x638); /* ftCommonData.x638 */
    port_swap32((u8*) p + 0x63C); /* ftCommonData.x63C */
    port_swap32((u8*) p + 0x640); /* ftCommonData.x640 */
    port_swap32((u8*) p + 0x644); /* ftCommonData.x644 */
    port_swap32((u8*) p + 0x648); /* ftCommonData.x648 */
    port_swap32((u8*) p + 0x64C); /* ftCommonData.x64C */
    port_swap32((u8*) p + 0x650); /* ftCommonData.x650 */
    port_swap32((u8*) p + 0x654); /* ftCommonData.x654 */
    port_swap32((u8*) p + 0x658); /* ftCommonData.x658 */
    port_swap32((u8*) p + 0x65C); /* ftCommonData.x65C */
    port_swap32((u8*) p + 0x660); /* ftCommonData.x660 */
    port_swap32((u8*) p + 0x664); /* ftCommonData.x664 */
    port_swap32((u8*) p + 0x668); /* ftCommonData.pressed_inputs */
    port_swap32((u8*) p + 0x66C); /* ftCommonData.released_inputs */
    port_swap32((u8*) p + 0x670); /* ftCommonData.x670 */
    port_swap32((u8*) p + 0x674); /* ftCommonData.x674 */
    port_swap32((u8*) p + 0x678); /* ftCommonData.x678 */
    port_swap32((u8*) p + 0x67C); /* ftCommonData.x67C */
    port_swap32((u8*) p + 0x680); /* ftCommonData.x680 */
    port_swap32((u8*) p + 0x684); /* ftCommonData.x684 */
    port_swap32((u8*) p + 0x688); /* ftCommonData.x688 */
    port_swap32((u8*) p + 0x68C); /* ftCommonData.x68C */
    port_swap32((u8*) p + 0x690); /* ftCommonData.x690 */
    port_swap32((u8*) p + 0x694); /* ftCommonData.x694 */
    port_swap32((u8*) p + 0x698); /* ftCommonData.x698 */
    port_swap32((u8*) p + 0x69C); /* ftCommonData.warpstarfall_drift_scaling */
    port_swap32((u8*) p + 0x6A0); /* ftCommonData.warpstarfall_drift_flat */
    port_swap32((u8*) p + 0x6A4); /* ftCommonData.warpstarfall_drift_max */
    port_swap32((u8*) p + 0x6A8); /* ftCommonData.x6A8 */
    port_swap32((u8*) p + 0x6AC); /* ftCommonData.x6AC */
    port_swap32((u8*) p + 0x6B0); /* ftCommonData.x6B0 */
    port_swap32((u8*) p + 0x6B4); /* ftCommonData.x6B4 */
    port_swap32((u8*) p + 0x6B8); /* ftCommonData.x6B8 */
    port_swap32((u8*) p + 0x6BC); /* ftCommonData.x6BC */
    port_swap32((u8*) p + 0x6C0); /* ftCommonData.x6C0 */
    port_swap32((u8*) p + 0x6C4); /* ftCommonData.x6C4 */
    port_swap32((u8*) p + 0x6C8); /* ftCommonData.x6C8 */
    port_swap32((u8*) p + 0x6CC); /* ftCommonData.x6CC */
    port_swap32((u8*) p + 0x6D0); /* ftCommonData.x6D0 */
    port_swap32((u8*) p + 0x6D4); /* ftCommonData.x6D4 */
    port_swap32((u8*) p + 0x6D8); /* ftCommonData.x6D8[0] */
    port_swap32((u8*) p + 0x6F0); /* ftCommonData.metal_armor */
    port_swap32((u8*) p + 0x6F4); /* ftCommonData.x6F4_unkDamage */
    port_swap32((u8*) p + 0x6F8); /* ftCommonData.x6F8 */
    port_swap32((u8*) p + 0x6FC); /* ftCommonData.x6FC */
    port_swap32((u8*) p + 0x700); /* ftCommonData.x700 */
    port_swap32((u8*) p + 0x704); /* ftCommonData.x704 */
    port_swap32((u8*) p + 0x708); /* ftCommonData.x708 */
    port_swap32((u8*) p + 0x70C); /* ftCommonData.x70C */
    port_swap32((u8*) p + 0x710); /* ftCommonData.x710 */
    port_swap32((u8*) p + 0x714); /* ftCommonData.x714 */
    port_swap32((u8*) p + 0x718); /* ftCommonData.kb_ice_mul */
    port_swap32((u8*) p + 0x71C); /* ftCommonData.x71C */
    port_swap32((u8*) p + 0x720); /* ftCommonData.x720 */
    port_swap32((u8*) p + 0x724); /* ftCommonData.x724 */
    port_swap32((u8*) p + 0x728); /* ftCommonData.x728 */
    port_swap32((u8*) p + 0x72C); /* ftCommonData.x72C */
    port_swap32((u8*) p + 0x730); /* ftCommonData.x730 */
    port_swap32((u8*) p + 0x734); /* ftCommonData.leadead_grab_timer_step */
    port_swap32((u8*) p + 0x738); /* ftCommonData.leadead_grab_break_threshold */
    port_swap32((u8*) p + 0x73C); /* ftCommonData.x73C */
    port_swap32((u8*) p + 0x740); /* ftCommonData.x740 */
    port_swap32((u8*) p + 0x744); /* ftCommonData.x744 */
    port_swap32((u8*) p + 0x748); /* ftCommonData.x748 */
    port_swap32((u8*) p + 0x74C); /* ftCommonData.x74C */
    port_swap32((u8*) p + 0x750); /* ftCommonData.x750 */
    port_swap32((u8*) p + 0x754); /* ftCommonData.x754 */
    port_swap32((u8*) p + 0x758); /* ftCommonData.x758 */
    port_swap32((u8*) p + 0x75C); /* ftCommonData.x75C */
    port_swap32((u8*) p + 0x760); /* ftCommonData.x760 */
    port_swap32((u8*) p + 0x764); /* ftCommonData.x764 */
    port_swap32((u8*) p + 0x768); /* ftCommonData.x768 */
    port_swap32((u8*) p + 0x76C); /* ftCommonData.x76C */
    port_swap32((u8*) p + 0x770); /* ftCommonData.x770 */
    port_swap32((u8*) p + 0x774); /* ftCommonData.x774 */
    port_swap32((u8*) p + 0x778); /* ftCommonData.passive_wall_vel_y_base */
    port_swap32((u8*) p + 0x77C); /* ftCommonData.damageice_gravity_mult */
    port_swap32((u8*) p + 0x780); /* ftCommonData.damageice_min_speed */
    port_swap32((u8*) p + 0x784); /* ftCommonData.damageice_speed_mult_on_break */
    port_swap32((u8*) p + 0x788); /* ftCommonData.damageice_rot_speed_min */
    port_swap32((u8*) p + 0x78C); /* ftCommonData.damageice_rot_speed_max */
    port_swap32((u8*) p + 0x790); /* ftCommonData.x790_damageice_unk */
    port_swap32((u8*) p + 0x794); /* ftCommonData.x794_damageice_unk */
    port_swap32((u8*) p + 0x798); /* ftCommonData.x798_damageice_unk */
    port_swap32((u8*) p + 0x79C); /* ftCommonData.damageice_dmg_time_reduction_mult */
    port_swap32((u8*) p + 0x7A0); /* ftCommonData.damageice_ice_size */
    port_swap32((u8*) p + 0x7A4); /* ftCommonData.damageicejump_escape_time */
    port_swap32((u8*) p + 0x7A8); /* ftCommonData.x7A8 */
    port_swap32((u8*) p + 0x7AC); /* ftCommonData.x7AC */
    port_swap32((u8*) p + 0x7B0); /* ftCommonData.x7B0 */
    port_swap32((u8*) p + 0x7B4); /* ftCommonData.x7B4_unkDamage */
    port_swap32((u8*) p + 0x7B8); /* ftCommonData.x7B8 */
    port_swap32((u8*) p + 0x7BC); /* ftCommonData.x7BC */
    port_swap32((u8*) p + 0x7C0); /* ftCommonData.x7C0 */
    port_swap32((u8*) p + 0x7C4); /* ftCommonData.kb_smashcharge_mul */
    port_swap32((u8*) p + 0x7C8); /* ftCommonData.x7C8 */
    port_swap32((u8*) p + 0x7CC); /* ftCommonData.x7CC */
    port_swap32((u8*) p + 0x7D0); /* ftCommonData.x7D0 */
    port_swap32((u8*) p + 0x7D4); /* ftCommonData.hit_weight_mul */
    port_swap32((u8*) p + 0x7DC); /* ftCommonData.x7DC */
    port_swap32((u8*) p + 0x7E0); /* ftCommonData.x7E0 */
    port_swap32((u8*) p + 0x7E4); /* ftCommonData.x7E4_scaleZ */
    port_swap32((u8*) p + 0x7E8); /* ftCommonData.unk_kb_angle_min */
    port_swap32((u8*) p + 0x7EC); /* ftCommonData.unk_kb_angle_max */
    port_swap32((u8*) p + 0x7F0); /* ftCommonData.x7F0 */
    port_swap32((u8*) p + 0x7F4); /* ftCommonData.x7F4 */
    port_swap32((u8*) p + 0x7F8); /* ftCommonData.x7F8 */
    port_swap32((u8*) p + 0x7FC); /* ftCommonData.x7FC */
    port_swap32((u8*) p + 0x800); /* ftCommonData.x800 */
    port_swap32((u8*) p + 0x804); /* ftCommonData.x804 */
    port_swap32((u8*) p + 0x808); /* ftCommonData.x808.x */
    port_swap32((u8*) p + 0x80C); /* ftCommonData.x808.y */
    port_swap32((u8*) p + 0x810); /* ftCommonData.x808.z */
    port_swap32((u8*) p + 0x814); /* ftCommonData.x814 */
}

/* ItemAttr: 0x84 bytes */
void port_swap_ItemAttr(void* p)
{
    port_swap32((u8*) p + 0x4); /* ItemAttr.x4_throw_speed_mul */
    port_swap32((u8*) p + 0x8); /* ItemAttr.x8 */
    port_swap32((u8*) p + 0xC); /* ItemAttr.xC_spin_speed */
    port_swap32((u8*) p + 0x10); /* ItemAttr.x10_fall_speed */
    port_swap32((u8*) p + 0x14); /* ItemAttr.x14_fall_speed_max */
    port_swap32((u8*) p + 0x18); /* ItemAttr.x18 */
    port_swap32((u8*) p + 0x1C); /* ItemAttr.x1C_damage_mul */
    port_swap32((u8*) p + 0x20); /* ItemAttr.x20.top */
    port_swap32((u8*) p + 0x24); /* ItemAttr.x20.bottom */
    port_swap32((u8*) p + 0x28); /* ItemAttr.x20.right */
    port_swap32((u8*) p + 0x2C); /* ItemAttr.x20.left */
    port_swap32((u8*) p + 0x30); /* ItemAttr.x30_unk.x */
    port_swap32((u8*) p + 0x34); /* ItemAttr.x30_unk.y */
    port_swap32((u8*) p + 0x38); /* ItemAttr.x38_grab_range.x */
    port_swap32((u8*) p + 0x3C); /* ItemAttr.x38_grab_range.y */
    port_swap32((u8*) p + 0x40); /* ItemAttr.x40.top */
    port_swap32((u8*) p + 0x44); /* ItemAttr.x40.bottom */
    port_swap32((u8*) p + 0x48); /* ItemAttr.x40.right */
    port_swap32((u8*) p + 0x4C); /* ItemAttr.x40.left */
    port_swap32((u8*) p + 0x50); /* ItemAttr.x50 */
    port_swap32((u8*) p + 0x54); /* ItemAttr.x54 */
    port_swap32((u8*) p + 0x58); /* ItemAttr.x58 */
    port_swap32((u8*) p + 0x5C); /* ItemAttr.x5c */
    port_swap32((u8*) p + 0x60); /* ItemAttr.x60_scale */
    port_swap32((u8*) p + 0x64); /* ItemAttr.destroy_gfx */
    port_swap32((u8*) p + 0x68); /* ItemAttr.x68 */
    port_swap32((u8*) p + 0x6C); /* ItemAttr.x6C */
    port_swap32((u8*) p + 0x70); /* ItemAttr.x70 */
    port_swap32((u8*) p + 0x74); /* ItemAttr.x74 */
    port_swap32((u8*) p + 0x78); /* ItemAttr.destroy_sfx */
    port_swap32((u8*) p + 0x7C); /* ItemAttr.x7C */
    port_swap32((u8*) p + 0x80); /* ItemAttr.x80 */
    if (port_claim((u8*) p + 0x0, 1)) { /* bitfields: ItemAttr.x0_is_heavy, ItemAttr.x0_78, ItemAttr.x0_hold_kind */
        u8* b = (u8*) p + 0x0;
        u32 be = ((u32) b[0] << 0);
        u32 host = 0;
        host |= ((be >> 7) & 0x1u) << 0;
        host |= ((be >> 3) & 0xFu) << 1;
        host |= ((be >> 0) & 0x7u) << 5;
        *(u8*) b = (u8) host;
    }
    if (port_claim((u8*) p + 0x1, 1)) { /* bitfields: ItemAttr.x1_1, ItemAttr.x1_3, ItemAttr.x1_4, ItemAttr.x1_5, ItemAttr.x1_67_cam_kind, ItemAttr.x1_8 */
        u8* b = (u8*) p + 0x1;
        u32 be = ((u32) b[0] << 0);
        u32 host = 0;
        host |= ((be >> 6) & 0x3u) << 0;
        host |= ((be >> 5) & 0x1u) << 2;
        host |= ((be >> 4) & 0x1u) << 3;
        host |= ((be >> 3) & 0x1u) << 4;
        host |= ((be >> 1) & 0x3u) << 5;
        host |= ((be >> 0) & 0x1u) << 7;
        *(u8*) b = (u8) host;
    }
}

/* ItemModelDesc: 0x10 bytes */
void port_swap_ItemModelDesc(void* p)
{
    port_swap32((u8*) p + 0x4); /* ItemModelDesc.x4_bone_count */
    port_swap32((u8*) p + 0x8); /* ItemModelDesc.x8_bone_attach_id */
}
