#!/usr/bin/env python3
"""Generate LSB-first script command layouts for the port.

Usage (run by port/build.ninja):
    gen_cmd_layouts.py src/melee/lb/types.h OUT.h

Subaction / item / stage event scripts are arrays of 32-bit words that game
code reads through bitfield structs (the `struct Command_00` ... `union
CmdUnion` block in src/melee/lb/types.h). MWCC allocates bitfields from the
most significant bit of the big-endian word; clang on x86 allocates from the
least significant bit. The port converts every script word to host order
(port_swap_script), so a field that MWCC places at word bits [31-a .. 32-a-w]
must sit at the same bit positions of the host u32.

For each struct in the block this emits an equivalent declaration:
  - bitfields in reverse order, preceded by an unnamed pad so they occupy
    the top bits of a 32-bit unit (MWCC fills from the top);
  - base types widened to u32/s32 with the same signedness (a u16 or u8
    bitfield on MWCC sits in the top half/byte of the word);
  - a leading byte array `u8 _0[N]` (bitfields continuing at byte N) keeps
    its whole words and starts the fields at bit 31 - 8 * (N % 4);
  - structs without bitfields and the union itself are copied verbatim.

Anything else fails loudly instead of guessing.
"""

import re
import sys

UNSIGNED = {"u8", "u16", "u32", "unsigned", "unsigned int"}
SIGNED = {"s8", "s16", "s32", "int", "signed", "signed int"}

MEMBER_BF = re.compile(r"^(.+?)\s+(\w+)?\s*:\s*(\d+)\s*;$")
BYTE_ARRAY = re.compile(r"^u8\s+(\w+)\s*\[\s*(0x[0-9A-Fa-f]+|\d+)\s*\]\s*;$")


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return re.sub(r"//[^\n]*", "", text)


def extract_block(src):
    start = src.index("struct Command_00 {")
    u = src.index("union CmdUnion {", start)
    end = src.index("};", u) + 2
    return src[start:end]


def transform_struct(name, body):
    members = [m.strip() + ";" for m in body.split(";") if m.strip()]
    fields = []
    lead_bytes = None
    plain = []
    for m in members:
        bf = MEMBER_BF.match(m)
        if bf:
            ctype, fname, width = bf.group(1).strip(), bf.group(2), int(bf.group(3))
            if ctype in UNSIGNED:
                host = "u32"
            elif ctype in SIGNED:
                host = "s32"
            else:
                raise SystemExit(f"{name}: unknown bitfield type '{ctype}'")
            fields.append((host, fname, width))
            continue
        ba = BYTE_ARRAY.match(m)
        if ba and not fields and lead_bytes is None:
            lead_bytes = (ba.group(1), int(ba.group(2), 0))
            continue
        if fields:
            raise SystemExit(f"{name}: member after bitfields: '{m}'")
        plain.append(m)

    if not fields:
        if lead_bytes is not None:
            raise SystemExit(f"{name}: byte array without bitfields")
        return "struct %s {\n%s\n};\n" % (name, "\n".join("    " + p for p in plain))
    if plain:
        raise SystemExit(f"{name}: mixes plain members and bitfields")

    total = sum(w for _, _, w in fields)
    top = 0
    out = []
    if lead_bytes is not None:
        aname, n = lead_bytes
        words, top_byte = divmod(n, 4)
        if words:
            out.append(f"    u8 {aname}[{words * 4}];")
        top = 8 * top_byte
    pad = 32 - top - total
    if pad < 0:
        raise SystemExit(f"{name}: {total} bits do not fit in one word")
    if pad:
        out.append(f"    u32 : {pad};")
    for host, fname, width in reversed(fields):
        out.append(f"    {host} {fname or ''} : {width};")
    return "struct %s {\n%s\n};\n" % (name, "\n".join(out))


def main():
    src = open(sys.argv[1]).read()
    block = strip_comments(extract_block(src))
    out = [
        "/* Generated by port/tools/gen_cmd_layouts.py from src/melee/lb/types.h."
        " Do not edit. */",
        "",
    ]
    pos = 0
    pattern = re.compile(r"(struct|union)\s+(\w+)\s*\{(.*?)\};", re.S)
    count = 0
    for m in pattern.finditer(block):
        if block[pos:m.start()].strip():
            raise SystemExit(f"unexpected text: {block[pos:m.start()].strip()[:60]}")
        kind, name, body = m.groups()
        if kind == "union":
            out.append("union %s {%s};\n" % (name, body))
        else:
            out.append(transform_struct(name, body))
            count += 1
        pos = m.end()
    if block[pos:].strip():
        raise SystemExit("trailing text after union CmdUnion")
    open(sys.argv[2], "w").write("\n".join(out))
    print(f"{sys.argv[2]}: {count} command structs")


if __name__ == "__main__":
    main()
