#!/usr/bin/env python3
"""Generate weak SDK stubs for symbols the port build leaves undefined.

Usage (from the repo root, after a `ninja -C port` link attempt):
    .venv/bin/python port/tools/gen_stubs.py <undefined-symbols.txt>

Reads one symbol per line, looks up each prototype in the SDK / game
headers, and writes port/src/sdk_stubs_gen.c with a weak definition per
symbol that returns 0. Because they are weak, a real implementation in any
other port/src/*.c file overrides the stub at link time; re-running the
generator is always safe. Symbols with no prototype found are listed in a
comment at the end so they can be handled by hand.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
HEADER_DIRS = [ROOT / "libs/dolphin/include", ROOT / "src"]
OUT = ROOT / "port/src/sdk_stubs_gen.c"

# Symbols that are data, or need hand-written code; never stubbed here.
# (OSPanic is declared twice in the SDK headers with different constness.)
SKIP = {"OSPanic"}


def load_headers():
    """Return a list of (include path, comment-stripped text)."""
    out = []
    for d in HEADER_DIRS:
        for h in sorted(d.rglob("*.h")):
            try:
                text = h.read_text(errors="replace")
            except OSError:
                continue
            out.append((h.relative_to(d).as_posix(), strip_comments(text)))
    return out


def strip_comments(s):
    s = re.sub(r"/\*.*?\*/", " ", s, flags=re.S)
    s = re.sub(r"//[^\n]*", " ", s)
    # Preprocessor lines (with continuations) become statement terminators
    # so a match can never run backwards into a #define.
    s = re.sub(r"^[ \t]*#(?:[^\n]*\\\n)*[^\n]*$", ";", s, flags=re.M)
    return s


def find_proto(headers, name):
    """Return (declaration text `ret name(args)`, include path) or None."""
    for path, text in headers:
        if name not in text:
            continue
        decl = find_proto_in(text, name)
        if decl:
            return decl, path
    return None


def find_proto_in(headers, name):
    # Match from the start of a declaration to the terminating ';' with
    # balanced parentheses; allow multi-line parameter lists.
    pat = re.compile(
        r"(?<![\w.])((?:[\w\s\*]+?)\b" + re.escape(name) + r"\s*\(([^;{}]*?)\))\s*;",
        re.S,
    )
    for m in pat.finditer(headers):
        decl = m.group(1)
        # The regex may run back into a previous statement; keep only the
        # tail after the last terminator.
        decl = re.split(r"[;}{]", decl)[-1]
        decl = " ".join(decl.split())
        decl = re.sub(r"^\s*extern\s+", "", decl)
        head = decl[: decl.index(name)]
        # Reject typedefs and function-pointer declarators (`void (*name)`);
        # function-pointer *parameters* are fine.
        if "typedef" in head or "(" in head:
            continue
        if not re.match(r"^[A-Za-z_]", decl):
            continue
        return decl
    return None


def return_type(decl, name):
    return decl[: decl.index(name)].strip()


def main():
    syms = [
        s.strip()
        for s in Path(sys.argv[1]).read_text().splitlines()
        if s.strip() and s.strip() not in SKIP
    ]
    headers = load_headers()
    includes = {"Runtime/platform.h"}
    stubs = []
    missing = []
    for s in syms:
        found = find_proto(headers, s)
        if found is None:
            missing.append(s)
            continue
        decl, path = found
        includes.add(path)
        rt = return_type(decl, s)
        body = "{}" if rt == "void" else f"{{ return ({rt}) 0; }}"
        stubs.append(f"STUB {decl} {body}")
    lines = [
        "// Generated by port/tools/gen_stubs.py. Do not edit by hand;",
        "// override a stub by defining the symbol in another port/src file.",
        "",
    ]
    lines += [f"#include <{i}>" for i in sorted(includes)]
    lines += ["", "#define STUB __attribute__((weak))", ""]
    lines += stubs
    lines.append("")
    if missing:
        lines.append("// No prototype found (handle by hand):")
        lines += [f"//   {m}" for m in missing]
        lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"{OUT.relative_to(ROOT)}: {len(syms) - len(missing)} stubs, "
          f"{len(missing)} without prototype: {' '.join(missing)}")


if __name__ == "__main__":
    main()
